### ISSUE TITLE
[BUG] "update_params=False" for statsmodels adapter should call apply

### ISSUE THREAD

**Issue by raphaccf** [sktime/sktime#1788]
The current logic of  `update(update_params=False)` in the `statsmodels` interfaces is not correct, the model simply produces predictions it would have made before the update, instead of applying the fitted model to new data.

Instead, the `apply` interface from `statsmodels` should be used appropriately, see the discussion below. Previously, this was available only for a few models, but seems to be a general interface point now.

---
**Describe the bug**

After estimated a model, I would like to make forecast after my test set, but without updating parameters (changing the model parameters). This is specially important for comparison, moreover to forecast with new data without changing the model.
I have tried to set `update_params=False` in "update()"  and in "update_predict_single()", but it seems that is not working. Dates (timestamp) are updated, but forecast is the same for the previous period. I do not know If I am doing something wrong, or it is a bug. I have an example with auto.arima (code bellow and pdf attached).

Kind regards

**To Reproduce**

```
import pandas as pd
import numpy as np
from sktime.datasets import load_airline
from sktime.forecasting.arima import AutoARIMA
from sktime import show_versions 
show_versions()
```
```
## data split
y=load_airline() ## total observations
y1 = y.head(y.shape[0]-6)  #train observations
y2 = y.tail(6) # test observations
```
```
forecaster = AutoARIMA(sp=12, suppress_warnings=True,random_state=123)
z=forecaster.fit(y1)
AutoARIMA(...)
y_pred = forecaster.predict(fh=[1,2,3,4,5,6])
### model configuration and parameters for train
z.summary()
```
```
y_pred_semfit = forecaster.predict(fh=[1,2,3,4,5,6]) ## o cutoff 1960-06
y_pred_semfit
```
```
## using a function from stkime for not update_params, but to forecast using the test portion of the data set (to append to train y1)
y_pred = forecaster.update_predict_single(y_new=y2, update_params=False)
y_pred
### dates changed, but forecasted values are the same as above
```

```
### just changing the input of the function
y_pred = forecaster.update_predict_single(y=y, update_params=False)
y_pred
```

```
### another function from stkime, without update/retrain model parameters using update_params=False
updated_model =  forecaster.update(y=y, update_params=False)
updated_model.predict()
```
```
### however, if we set "update_params=True", time for command excution increase and forecasted values change
updated_model =  forecaster.update(y=y2, update_params=True)
updated_model.predict()
```

```
## but model parameters/configuration are different
updated_model.summary()
```

```
### using another function from Sktime, .fit_predict, the same results as above
y_pred = forecaster.fit_predict(y,fh=[1,2,3,4,5,6])
y_pred
```
[Sktime_update_model.pdf](https://github.com/alan-turing-institute/sktime/files/7757528/Sktime_update_model.pdf)

`forecaster.summary()`

**Comment by fkiraly** [comment]
@raphaccf, thanks for reporting.
It sounds like this might be an issue specific to the AutoARIMA interface, will investigate.
Perchance, have you observed this in other estimators?

**Comment by raphaccf** [comment]
Thanks for your response. Actually, I also tested with auto.ets, and I identified  the same behavior.

**Comment by fkiraly** [comment]
Hm, yes, I'm able to reproduce this on my local system (3.8, win, main).
Any comments that help tracking down the issue are appreciated.

My first suspicion was that the model's `cutoff` is not updated correctly, hence the `fh` will be relative to the wrong `cutoff`, from `fit` rather than `update`. But that's not true, the `cutoff` seems to be updated correctly (by the base class).
So it does not seem to be a framework issue.

Hence, I now suspect that there is some systematic issue in how the `fh` is passed to the models, in the concrete classes.
If correct, the wrapped models should be asked to forecast at [number of time points seen in update] plus [relative fh], but probably they are just asked to forecast at [relative fh], since the implementer did not anticipate a situation in which the time point last seen is *not* the same as the time point last fitted.

**Comment by fkiraly** [comment]
@raphaccf, I'll look into this, since it seems like an important use case.

If you have time, would you be able to help with a list of the estimators where you think this is a problem?
You can loop over all forecasters by using `registry.all_estimators(estimator_types="forecaster")`.
I'll check AutoARIMA and AutoETS first.

**Comment by fkiraly** [comment]
Just for information, if anyone else is looking at this:
the bug is a discrepancy between conceptual scientific behaviour and actual behaviour.
Running `update(update_params=False)` over 6 time periods and then asking for a forecast 1 period ahead (with the model fitted before the update) should in generael not be identical with a forecast for the 1st period of the updated time period, from the data previously seen.

**Comment by fkiraly** [comment]
Another question is how, if at all, one would test this. The forecaster is interface compliant, it just doesn't output what one would expect of the specified behaviour if an ARIMA model were used.

**Comment by fkiraly** [comment]
>If correct, the wrapped models should be asked to forecast at [number of time points seen in update] plus [relative fh], but probably they are just asked to forecast at [relative fh], since the implementer did not anticipate a situation in which the time point last seen is not the same as the time point last fitted.

Yes, I think that's exactly what is happening. `pmdarima` assumes an internal cutoff which is always the last data point seen. The internals are using the `sktime` forecaster's cutoff (which has been updated) instead of the `pmdarima` cutoff, which leads to this behaviour in the one case where a discrepancy can arise (the `update(update_params=False)` case).

**Comment by fkiraly** [comment]
@raphaccf, I've looked into this now. It seems there are two things happening:

* cutoff handling in `sktime`'s interface to `pmdarima` - due to that, the `pmdarima` is asked to predict with a cutoff, as if `update(update_params=False)` never happened
* `pmdarima`, and `statsmodels` on which it is based, does not seem to be able to make forecasts with fixed model parameters on data different from which it was fitted on. I may just be missing how to call it, but neither `pmdarima` nor `statsmodels` `fit` and `predict` seem to offer this functionality.

If the second is correct, the best we could do at `sktime` is to return the forecasts that the model would have produced for the same time stamps *before* `update` was called.

May be worth asking a question on `statsmodels` or `pmdarima`, and if the lack of this feature is confirmed, then raising an issue?

**Comment by raphaccf** [comment]
Franz, thank you so much for all the energy you put into this investigation. I understand the aspects you mentioned, and I will follow your suggestion and ask them. Thanks again.

**Comment by fkiraly** [comment]
well, there is still an `sktime` aspect to this, namely, intended behaviour on `update_params=False` - it's not *just* a `statsmodels issue (see above, "two things happening"). I'll put the `sktime` specific one on the todo list, hence I'm reopening the issue. 

Depending on the answer in `statsmodels`, there may also be actions arising (a bugfix, or a "suggested enhancement")

**Comment by raphaccf** [comment]
Sorry Franz, I'm new to github discusssions, but you mean: open my issues respectavily int statsmodels and pmdarima github's Issues, than get a link from it and post it here?

**Comment by fkiraly** [comment]
>Sorry Franz, I'm new to github discusssions, but you mean: open my issues respectavily int statsmodels and pmdarima github's Issues, than get a link from it and post it here?

Yes, exactly, so this issue links to the other issue(s) on the relevant topic, in the right package(s).
I was implicitly referring to this statement of yours

> I understand the aspects you mentioned, and I will follow your suggestion and ask them.

which made me think you had already opened issues or were planning to.

I can also open the issues if you'd prefer me to do this, btw.

**Comment by raphaccf** [comment]
I haven't opened them yet. I will feel more comfortable (avoid any mistakes in the process) if you do it, sorry.

**Comment by fkiraly** [comment]
relevant issue already exists, was opened 11 days ago: https://github.com/statsmodels/statsmodels/issues/7981

**Comment by fkiraly** [comment]
also seems like there's a workaround for `ARIMA` at least, via the `apply` function

**Comment by fkiraly** [comment]
looks like it´s becoming a general interface point now: https://github.com/statsmodels/statsmodels/pull/8006
This should be an easy thing to interface, so putting this at the top.

**Comment by fkiraly** [comment]
FYI @raphaccf, I´ve updated the header of this issue, so it´s now an instruction what to do.

**Comment by fkiraly** [comment]
@chillerobscuro, some answers to questions from slack to have them here:

>As far as I can tell, it is conceptually quite simple and I'm just utilizing the somewhat new apply function in statsmodels to update the "seen data" which will be the cutoff for new predictions. My questions are:
Is it clear what the entire set of sktime models with direct statsmodel  interfaces are? It seems from the ticket that it may be unknown. Should I just search the repo for all _StatsModelsAdapter instances?

Yes, that's right, although the generic `_update` behaviour would sit in the adapter class. 

> Where do you imagine the fix going? Will it likely be in the _StatsModelsAdapter somewhere, or is there a deeper base class or something that would make more sense?

Consistent with the above, in `_StatsModelsAdapter`. Although, in the past, some instances in `statsmodels` have been inconsistent, so some instances may also have to be fixed.

>To find all models with the larger problem It'd be easy to run through all the estimators and see which ones give the exact same prediction after an update, but that would include the pmdarima and likely other interfaces as well.

Hm, it might be worthwhile to write a test for that, just to see which models may or may not have a problem.
It should be pointed out that some models with the behaviour (update does not matter) are not faulty, e.g., the naive forecaster with "last value carry forward".

>Any other pitfalls or tips?

There might be some interaction with subsetting in `pandas`, where the `freq` attribute of `index` disappears, but that's just a hunch.

**Comment by chillerobscuro** [comment]
Thanks @fkiraly, I think I have a path forward: I will add an `_update()` method to `_StatsModelsAdapter`. Should I copy over the logic from the base class `_update` with regards to `if update_params = True` and `elif self.is_composite()`? Or somehow only call the new custom `_update` if `update_params=False`?

Also just to add info to this ticket, the `statsmodels` `apply` function assumes the new data is unrelated to the training data. The `append` and `extend` functions match what users will expect of an `update()` method so I will use them instead, likely `append` as it keeps the results objects for both the old and new data as shown [here.](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.mlemodel.MLEResults.append.html#statsmodels.tsa.statespace.mlemodel.MLEResults.append)

**Comment by fkiraly** [comment]
>Thanks @fkiraly, I think I have a path forward: I will add an `_update()` method to `_StatsModelsAdapter`. Should I copy over the logic from the base class `_update` with regards to `if update_params = True` and `elif self.is_composite()`? Or somehow only call the new custom `_update` if `update_params=False`?

Both. From a logics/content perspective, I think your first instinct is correct, but you need to be aware that copy-paste is an anti-pattern in coding, at the least a serious code smell.

So, I would make a new custom `_update` but call `super._update` if `update_params=True`, or something else that minimizes copy-pasting.

>Also just to add info to this ticket, the `statsmodels` `apply` function assumes the new data is unrelated to the training data. The `append` and `extend` functions match what users will expect of an `update()` method so I will use them instead, likely `append` as it keeps the results objects for both the old and new data as shown [here.](https://www.statsmodels.org/dev/generated/statsmodels.tsa.statespace.mlemodel.MLEResults.append.html#statsmodels.tsa.statespace.mlemodel.MLEResults.append)

Ok, the one thing to keep in mind is that `update` could be called with data that intersects the previously seen data.

**Comment by chillerobscuro** [comment]
> So, I would make a new custom _update but call super._update if update_params=True, or something else that minimizes copy-pasting.

This makes sense, and the following logic does seem to work:

```    def _update(self, y, X=None, update_params=True):
        if update_params:
            super()._update(y, X, update_params=True)
        else:
            # new logic here
```
However this makes false the warning in the base class `_update`, as it will no longer be true. It is currently 
```
warn(
                f"NotImplementedWarning: {self.__class__.__name__} "
                f"does not have a custom `update` method implemented. "
                f"{self.__class__.__name__} will be refit each time "
                f"`update` is called with update_params=True."
            )
```
Why do we need a warning that we're refitting if they are passing `update_params=True`? Isn't that expected?

I don't quite comprehend is the base class `elif self.is_composite():` logic, as I haven't worked with composite models in `sktime`. Can this be ignored for this ticket, and just use another `super()` call if  `self.is_composite == True` ?

> The one thing to keep in mind is that update could be called with data that intersects the previously seen data.

This does add complexity. For a true "update", it looks like `statsmodels` has pretty good warnings when the data doesn't fit: `ValueError: Given endog does not have an index that extends the index of the model.`. Can we just rely on that if the user doesn't pass data with a correct time index?

If the data passed doesn't immediately follow the original training data, ie completely different or just overlapping, we can just use `apply`, as you seem to be getting at, and is pretty simple. But maybe this should live in a different function like `apply_fitted_params_to_new_data` or something to avoid confusion on what update is doing?

**Comment by fkiraly** [comment]
> Why do we need a warning that we're refitting if they are passing update_params=True? Isn't that expected?

It's not in general expected, because many methods have a faster update than a fit method.

I think it also deserves a warning, becaue it can mean high compute usage if users do a rolling update, say, with one data point each - this would lead to many refits.

Regarding the design with `super`, I see how the warning could be a problem. 

I would suggest to do the following in a separate PR (which you merge into this):
move the warning to `update` in `BaseForecaster`, and raise it only when the `_update` method is overridden. This can be checked by `self._has_implementation_of("_update")`.

That would raise the warning only if `_update` is not overridden, i.e., not in the `super._update` case.

**Comment by fkiraly** [comment]
> This does add complexity. For a true "update", it looks like statsmodels has pretty good warnings when the data doesn't fit: ValueError: Given endog does not have an index that extends the index of the model.. Can we just rely on that if the user doesn't pass data with a correct time index?

Unfortuantely, no.
But, we could take the set difference of index and subset?

**Comment by chillerobscuro** [comment]
> Unfortuantely, no.

Just curious, why not? Wouldn't it come through and be descriptive of the issue?

> But, we could take the set difference of index and subset?

How do I access the data that the model was fit on?

I could go either way on this. It's more user friendly to implicitly take the set difference, but it's also fair to expect users to input non-overlapping data. If we try to take a subset and the data is incorrect, wont it just fall to the `statsmodels` error anyway?

**Comment by chillerobscuro** [comment]
Can I request a sanity check before I continue? I am using `sktime` `SARIMAX` as an example of a model that uses the `_StatsModelsAdapter`. When I run the following code it seems to behave in a way that does not need fixing. If `update_params=True`, it runs the optimization before both predict steps, and outputs a prediction at the correct index position, directly after the last `update` value.

If `update_params=False`, then it does not show the optimization being run after `update()` is called. The prediction is different than the one from the previous case, but has the correct index, showing that the `update()` did work.

As far as I can tell everything is working as hoped - when running this code and the same block with `update_params` set to `True`, I am not seeing the "new index but same prediction value" that we were seeing with the `pmdarima` wrapped models, and I am seeing a difference between the refit model and the simply "updated" one.
```
from sktime.datasets import load_airline
from sktime.forecasting.sarimax import SARIMAX
ind = 24
y = load_airline()
mod = SARIMAX()
mod.fit(y.iloc[:si])
print(mod.predict(fh=1))
mod.update(y.iloc[ind:ind+3], update_params=False) # update data with 3 new steps
# mod._y is successfully updated and predict will forecast 3 steps past the original training data
print(mod.predict(fh=1))
```
I am surprised because I actually can't tell where we send the data to the underlying `statsmodels` model. I see the `update` method calls `self._set_cutoff_from_y` and `self._update_y_X` but as far as I can tell those don't seem to reach into the underlying `statsmodel`.

**Comment by chillerobscuro** [comment]
I've managed to re-identify the erroneous behavior. The `_StatsModelsAdapter` models do not refit when `update_parms=False`, and do update the index to the new data passed to `update`, both good behaviors. 

However, the values passed to `update` do not affect the forecast predictions at all - they are the same as if you just forecast with a horizon equal to `fh`+`length of update values` before calling the update.

I'm still trying to track down the question from the last paragraph of the above post, understanding how the correct update indices are passed to the underlying model, but not actually using the correct `statsmodels` `append` behavior.

**Comment by fkiraly** [comment]
>> Unfortuantely, no.

>Just curious, why not? Wouldn't it come through and be descriptive of the issue?

The interface contract allows the user to pass data that has already been seen.
