### ISSUE TITLE
Time series regression: refactoring time series classifiers

### ISSUE THREAD

**Issue by mloning** [sktime/sktime#212]
Many of the classification algorithms can be refactored into regression algorithms, most of this should be straightforward due to the modular structure of the algorithms, however some care is needed in factoring out base classes from which both regressors and classifiers can inherit. 

Also see this [paper](https://arxiv.org/pdf/2006.12672.pdf).

**Comment by shuyanmei** [comment]
Can you include the window size in ComposableTimeSeriesForestRegressor as well? So we can predict for few days ahead for multivariate time series.  Thank you.

**Comment by mloning** [comment]
@shuyanmei which window size do you mean? It's a regressor, not a forecaster. For temporal forward predictions, you should use `make_reduction` from `sktime.forecasting.compose`

**Comment by shuyanmei** [comment]
@mloning , thank you for the reply. I think make_reduction is the one I am looking for. Another question is that I am trying to use lightgbm with sktime to predict a few days ahead with multiple features (include categorical features). Lightgbm in scikit-learn package can deal with categorical features directly as string format in 'fit' function without the need of encoding first. Since sktime is using scikit-learn's lightgbm, but seems that this function is not supported. If I understand correctly, based on https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/compose/_reduce.py, it stacks the X, y data together and assign it to a initialized numpy ndarray first, and then fit to model. But 'string' can not be saved into numpy array, hence it caused the problem. I also didn't find tutorial on how to predict n-days ahead for multivariate data including categorical feature on the documentation. Since it is a very common scenario in reality, I am wondering is it supported so far and it is still underdevelopment?

**Comment by mloning** [comment]
I think that's right, currently the reduction approach only handles type-homogenous data due to the use of numpy arrays. A quick fix may be to encode the categorical data first.

**Comment by fkiraly** [comment]
the less quick but better fix is joining the `sktime` dev days next week and contribute to the refactoring forecasting and introducing multivariate functionality :smiley:

**Comment by shuyanmei** [comment]
> the less quick but better fix is joining the `sktime` dev days next week and contribute to the refactoring forecasting and introducing multivariate functionality 😃

Just registered for the dev days and I am looking forward to it 😄

**Comment by fkiraly** [comment]
I think this has concluded at some point between 2021 and now.

The most important classifiers exist as regressors.
