### ISSUE TITLE
[BUG] SignatureTransformer and SignatureClassifier was incorrect, erroneously transpose numpy3D arrays

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2374]
As far as I can tell, both `SignatureClassifier` and `SignatureTransformer` were giving incorrect results.

The reason is that the signature transform adopted the wrong specification for numpy 3D arrays, namely, `(n_instances, n_timepoints, n_columns)` instead of the official `(n_instances, n_columns, n_timepoints)`.

`SignatureClassifier` was assuming the latter, `SignatureTransformer` the former. The mix-up was not detected since `SignatureTransformer` still would produce a table output, just not the one which the intention to produce was.

FYI @jambo6, @TonyBagnall.

I think this is fixed in https://github.com/alan-turing-institute/sktime/pull/2369, although it means that the `depth` parameters chosen are no longer compatible and raise errors, and the "expected results" are also no longer right.

How do we go about this?
Perhaps we should confirm first whether I am right, @jambo6, @TonyBagnall?

**Comment by jambo6** [comment]
Hello,

So the signature module was definitely working fine, but I appreciate some things have needed to be changed around.

So we always work with paths of shape [N, L, C] whereas sktime uses [N, C, L]. I took the lazy route of just flipping the C, L axes in the SignatureTransformer class and keeping everything the same as my existing stuff for the remainder of the code. I realise this makes the augmentation classes usable only via `SignatureTransformer` that handles the axes flipping. If it is desired for them to become general classes then they need adapting. 

`SignatureClassifier` is just a wrapper around `SignatureTransformer`. So they are not mixed up since `SignatureClassifier` just calls `SignatureTransformer` which flips the axes and performs the signature operations. Thus is does not need to happen in `SignatureClassifier`.

One options, which appears to be the one taken, would perform a transpose for each of the augmentations, but must also happen in the `esig.stream2sig/stream2logsig` function - it appears not to have been added to the`esig` bits. 

I don't understand what this issue with depth is. The new code just seems to change the `depth` attribute to `sig_depth` but then call `depth = self.sig_depth` in the transform function. Not sure why this was necessary.

**Comment by fkiraly** [comment]
I see, thanks for confirming!

I did the flipping in this PR on all the components too:
https://github.com/alan-turing-institute/sktime/pull/2369
I hope this is still correct?

>I don't understand what this issue with depth is.

Constructor must write all parameters to self, *to a parameter of the same name*, or it will not be scikit-learn compliant (e.g., will throw an error if you attempt to print).

**Comment by jambo6** [comment]
Doing the flips as described looks fine. It would perhaps be a bit neater to implement as an `axflip` decorator of some description, but up to you of course. Neater still would of course just be to rewrite them for [N, C, L] arrays.

The bit that is missing is
```
signature = np.stack(
    [transform(x[window.start : window.end]) for x in data]
).reshape(data.shape[0], -1)
```
needs to go to
```
signature = np.stack(
    [transform(x[window.start : window.end].T) for x in data]
).reshape(data.shape[0], -1)
```
since currently `x` would be of shape `[C, W]` where `C` the number of channels and `W` is the length of the window due to the axflip at the start. `esig` requires `[W, C]`.

Regarding depth, in that case, it would be neater to ignore `depth` altogether and just to call `self.sig_depth`.

**Comment by fkiraly** [comment]
>It would perhaps be a bit neater to implement as an axflip decorator 

I think it would be neater if the internal code would just use the right axes.

The "systematic" way, i.e., if it occurs often, would be the introduction of an mtype `numpy3D_flipped` or similar, since input/output conversion concerns are managed via `convert` in the `datatypes` module, currently.
A decorator would duplicate the locus of this concern and would not be preferable.

**Comment by fkiraly** [comment]
> The bit that is missing is

In the PR?

Would you kindly mind leaving a comment there, if it is missing?

**Comment by TonyBagnall** [comment]
my preference would have been to leave it all as is (if it aint broke...) but make the helper functions that require the  [N, L, C] private, then to raise an issue to refactor it all to work with  [N, C, L] to see if anyone wants to take it on.

**Comment by fkiraly** [comment]
> my preference would have been to leave it all as is (if it aint broke...) but make the helper functions that require the [N, L, C] private, then to raise an issue to refactor it all to work with [N, C, L] to see if anyone wants to take it on.

@TonyBagnall, the refactor is a refactor, it does not change functionality.
The helpers remain private, but are upgraded to conform with the transform interface in cases where they claim they do.

**Comment by fkiraly** [comment]
> if it aint broke...

PS: as the refactor apprently uncovered, it *was* broke all along? At least in parts...

**Comment by TonyBagnall** [comment]
Ah I misunderstood, I thought @jambo6 said it was fine before. @MatthewMiddlehurst this will impact our pipeline results

**Comment by fkiraly** [comment]
> Ah I misunderstood, I thought @jambo6 said it was fine before

He did, but now I think he changed his opinion?
As all wise people, in the wake of sufficient evidence...

**Comment by fkiraly** [comment]
@jambo6, have you investigated this?

Is the current state error-free? If so, we can close this.

**Comment by TonyBagnall** [comment]
I have stepped through this transformer to make sure the dimensions are correctly handled throughout, and I have run the related classifier on the uni and multi archive data, generating plausible results, so I am happy it is error free
