### ISSUE TITLE
[BUG] windows install failure under current doc workflow due to scipy dll problem 

### ISSUE THREAD

**Issue by TonyBagnall** [sktime/sktime#2586]
**Describe the bug**
Windows CI is currently failing, see for example

https://github.com/alan-turing-institute/sktime/pull/2491

**To Reproduce**
my workflow on windows for a new install has been this

conda create -n sktime python=3.8
conda activate sktime
conda install -c conda-forge pystan
conda install -c conda-forge prophet
conda install -c conda-forge scipy
pip install -e .[all_extras,dev]

I have installed like this for months on several machines without problem. Although @aiwalter says the scipy is not required, I'm pretty sure I got this from the CI, maybe from @lmmentel ?. If I do the above from main on 0.11.3 now, I get the following
![image](https://user-images.githubusercontent.com/9594042/166102852-46ec2294-2f46-4027-99c3-79aad466e23a.png)

FileNotFoundError: Could not find module 'C:\ProgramData\Anaconda3\envs\sktime-temp2\lib\site-packages\scipy\.libs\libbanded5x.TNNMG3IXHGJK7NIBT5J6YPEO5XWTOQAJ.gfortran-win_amd64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

this suggests that sci-py is being installed twice, confusing the compiler which is looking for the wrong dll. This is fixed locally with

> pip uninstall scipy
> pip install scipy 

runs fine after that. Note, I have just gone through with this

conda create -n sktime python=3.8
conda activate sktime
conda install -c conda-forge pystan
conda install -c conda-forge prophet
pip install -e .[all_extras,dev]

and I still get the same dll problem, also fixed by an uninstall and install with pip

**Comment by lmmentel** [comment]
There was a recently fixed issue #2561 that should've fixed that by changing the channel to install `scipy` from. There is definitely thing we can improve in when it comes to installation on windows since we are essentially using two packages managers simultaneously - conda and pip and in my option will be problematic to maintain. 

Hopefully once `prophet` release wheels on pypi we'll be able to stick to pip and eliminate conflict. 

Alternatively we could create an `environment.yml` for pure conda installations.

**Comment by TonyBagnall** [comment]
This has been resolved, no longer an issue, I've done a full windows install recently
