### ISSUE TITLE
[ENH] removing redundant parameter `start_with_window` in `ExpandingWindowSplitter`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2678]
The parameter `start_with_window` in `ExpandingWindowSplitter` is redundant with `initial_window`.

If `start_with_window` is `False` (a non-default), the `ExpandingWindowSplitter` behaves as if `initial_window` were zero.
However, `initial_window` cannot be set to zero.

I feel the above choice contributes to user confusion.

I think `start_with_window` should just be removed, and `initial_window=0` should be possible, mapping on the prior behaviour of `start_with_window=False`.

The change needs to be accompanied by deprecation, as follows:

* `initial_window=0` should become possible
* `start_with_window` is retained, but a value of `False` raises a deprecation message along the lines of "please use `initial_window=0` instead"

For deprecation conventions in `sktime`, see this guide:
https://www.sktime.org/en/stable/developer_guide/deprecation.html

**Comment by fkiraly** [comment]
FYI @keepersas

**Comment by chillerobscuro** [comment]
@fkiraly I'm taking this on and already have code that may be working as planned. My questions before I submit the PR:
1. Do we also want to remove `start_with_window` for `SlidingWindowSplitter`? The design choice of allowing `initial_window=0` replace `start_with_window` would seem the same to me but slightly different implementations.
2. If we do want to remove this for `SlidingWindowSplitter`, what is the expected behavior for the params `initial_window=0`, `window_length=4`, and `step_size=2`? The first training window would be `[]`. Would the second follow the logic of `step_size` and contain `[0,1]` (where the end of the training set took a step of 2 past the last one), or would it always obey `window_length` and have a next two training sets of `[0,1,2,3]` and `[2,3,4,5]` (where the end of the training window went up by more than `step_size`)?

After the initial empty window we can only respect one of `step_size` or `window_length` in this case.

**Comment by fkiraly** [comment]
> 1. Do we also want to remove `start_with_window` for `SlidingWindowSplitter`? The design choice of allowing `initial_window=0` replace `start_with_window` would seem the same to me but slightly different implementations.

Hm, not sure what that would be.
What is the current behaviour if `start_with_window` is `False`?

**Comment by chillerobscuro** [comment]
> What is the current behaviour if start_with_window is False?

The current implementation respects the `step_length`, because the internal logic increments by that length to create each new window.
```
splitter = SlidingWindowSplitter(fh=[1,2], step_length=2, window_length=4, start_with_window=False)
list(splitter.split(ts))

out >
[(array([], dtype=int64), array([0, 1])),
 (array([0, 1]), array([2, 3])),
 (array([0, 1, 2, 3]), array([4, 5])),
 (array([2, 3, 4, 5]), array([6, 7])),
 (array([4, 5, 6, 7]), array([8, 9]))]
```

> Either case, I would say this should be a separate PR/issue.

The changes I've made for this issue in `BaseWindowSplitter` would change the design for both subclasses (to allowing `initial_window=0` and would keep the behavior described above the same for the `SlidingWindowSplitter` (respecting `step_length`. In this case could this just be one PR?

**Comment by chillerobscuro** [comment]
Also @fkiraly could you point me to an example of correct usage for `deprecated` when it is just for a piece of functionality and not a whole method, function, or class like in the above document? That could also be a potential opportunity for improvement in [the doc](https://www.sktime.org/en/stable/developer_guide/deprecation.html) for next time somebody has the same question.

**Comment by fkiraly** [comment]
I think this was not carried out correctly, I unfortunately did not spot that in the PR review (did I review that?)

It looks like the parameter got removed, but no further logic got introduced, e.g., dealing with the parameter in the base class or super call.

**Comment by fkiraly** [comment]
FYI @chillerobscuro - don't worry, this was a bit subtle and not easy to spot.

Learning moment: the code should have been tested (by author and PR reviewer!) in its state after the suggested deprecation actions.

Thanks for your contribution!

**Comment by fkiraly** [comment]
done in https://github.com/sktime/sktime/pull/3953 now
