### ISSUE TITLE
[DOC] Redirect link to latest documentation is broken on several pages.

### ISSUE THREAD

**Issue by ngupta23** [sktime/sktime#2729]
#### Describe the issue linked to the documentation

Google search on topics related to sktime take me to old documentation for some reason (v0.5.3 in this case). 

https://www.sktime.org/en/v0.5.3/api_reference/modules/auto_generated/sktime.transformations.series.impute.Imputer.html

On this page, if I click on the banner on top to take me to 0.11.4 documentation, it does not work.

https://www.sktime.org/en/v0.11.4/api_reference/modules/auto_generated/sktime.transformations.series.impute.Imputer.html

![image](https://user-images.githubusercontent.com/33585645/171314317-a582e481-7b0e-4917-bd8a-e22e1c948e4c.png)

#### Suggest a potential alternative/fix

Can the redirection issue be fixed? I have noticed this on several pages.

**Comment by fkiraly** [comment]
Yes, I'm painfully aware of this too, I also always get this a lot when searching, google directing to pre-doc-refactor locations.

I have no good solution though that I can think of. Since any update to the docs will lead to a version with a newer version number, and I do not know whether retroactive changes are even possible (e.g., to change the redirection links in bulk).

**Comment by fkiraly** [comment]
Tagging "good first issue", for people who are experts with readthedocs.

**Comment by fkiraly** [comment]
> @fkiraly Is the root cause that the module structure for newer versions different from the older ones (0.5.3)?

Yes, correct.

**Comment by arampuria19** [comment]
While going through the README.md file, I saw fbprophet hyperlink broken in features section and tried fixing that.

**Comment by fkiraly** [comment]
now resolved by new doc reword (a while ago)
