### ISSUE TITLE
[ENH] `sktime` transformer wrapper for `pywatts` `StepInformation`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#2918]
for exploration: let's try wrapping `pywatts` `StepInformation` in an `sktime` transformer. To explore what the current interface points would be.

**Comment by fkiraly** [comment]
FYI @benheid, @kalebphipps, @smeisen

**Comment by fkiraly** [comment]
(you need to reply so I can assign)

**Comment by benHeid** [comment]
I implemented a pyWATTS Wrapper (https://github.com/benHeid/sktime/blob/pywatts_wrapper/sktime/forecasting/pywatts.py) as a Transformer. And tested it with a very simple pipeline (https://github.com/benHeid/sktime/blob/pywatts_wrapper/example_pywatts.py). 

I identify the following open questions:
* How do we merge the y and the X input that are provided to fit, since the pywatts pipeline does only expect one data input (with potentially multiple columns).
* Is it a good way to implement such a wrapper as a transformer. Because sometimes the pipeline needs to be fitted. I solve this by overriding the `fit` method of the transformer.
* It is important that the input provided to `fit` and `_transform` is a pandas DataFrame since the pywatts pipeline needs column names to provide the correct data to the correct modules/(transformer) inside of the pipeline.


Note:
* I only tested the very simple scenario. I am not sure if this works with multiple output columns, input columns etc.

**Comment by fkiraly** [comment]
> How do we merge the y and the X input that are provided to fit, since the pywatts pipeline does only expect one data input (with potentially multiple columns).

I'd suggest, let's just ignore `y`, if there is no "designated column" field in pywatts.

**Comment by fkiraly** [comment]
> Is it a good way to implement such a wrapper as a transformer. Because sometimes the pipeline needs to be fitted. I solve this by overriding the `fit` method of the transformer.

the tag `fit_is_empty` needs to be set to `False`, then `_fit` is not skipped

**Comment by benHeid** [comment]
@fkiraly I suppose this issue is not relevant any more. Should we close it?

**Comment by fkiraly** [comment]
I suppose - just to confirm, could you quickly summarize how this is no longer required by the re-design?

**Comment by benHeid** [comment]
Not required anymore since we decided to rewrite the graph pipeline from scratch in sktime instead of wrapping the pywatts-based implementation and its elements that are required in sktime.
