### ISSUE TITLE
[ENH] support for scikit-learn 1.2

### ISSUE THREAD

**Issue by celestinoxp** [sktime/sktime#3053]
sktime 0.13.0 has requirement scikit-learn<1.2.0,>=0.24.0, but you have scikit-learn 1.2.dev0.

sktime 0.13.x should support future version of scikit-learn (1.2). I think we should work to support it...

more info: https://scikit-learn.org/dev/whats_new/v1.2.html

**Comment by fkiraly** [comment]
We've had repeated discussions around defensive version bounds and ultimately want to remove them, FYI @lmmentel, @aiwalter, @freddyaboulton.

With `statsmodels` and `sklearn`, though, we keep finding these legacy private imports, like this: https://github.com/alan-turing-institute/sktime/issues/3037
which, so far, with regularity, has broken `sktime` at each minor upgrade of these packages (fault being, of course, with the legacy private imports inside `sktime`).

Personally, I agree we should remove defensive version bounds eventually, but only after one or two of the minor upgrades go well without `sktime` breaking. For `sklearn`, we already know that 1.2 is not on the list because of the `_pprint` import #3037...

**Comment by celestinoxp** [comment]
> For sklearn, we already know that 1.2 is not on the list because of the _pprint import https://github.com/alan-turing-institute/sktime/issues/3037...

ultados da tradução
I believe that if we take the time to analyze changes to other libraries we can be quite up to date. Just take a look at the changelogs for the versions in development.

I like to see the package changelogs, I love seeing the improvements come to fruition. It's just advantages!

who doesn't like to see this?! https://scikit-learn.org/stable/whats_new/v1.1.html#version-1-1-1

**Comment by lmmentel** [comment]
Sklearn 1.2 is not released yet so it is hard to make definite comments about compatibility at this point.

**Comment by jorenham** [comment]
sklearn 1.2.0 has been released
https://github.com/scikit-learn/scikit-learn/releases/tag/1.2.0

**Comment by fkiraly** [comment]
Forgot to close this. `sktime` is compatible with `sklearn 1.2.x` since `sktime 0.15.0`.
