### ISSUE TITLE
[ENH] Include all prediction results of Prophet model (e.g. upper and lower bounds, ...)

### ISSUE THREAD

**Issue by ealizadeh-via** [sktime/sktime#3115]
It would be great if for prophet model, you have a method to get all prediction results instead of only `yhat`. fbprophet model generates many useful informations along with the forecast of the target that currently is not exposed in the sktime wrapper. 
Some of these columns are `trend`, `yhat_upper`, `yhat_lower`, ... and many more data about the components of the forecast results.

**Comment by fkiraly** [comment]
@ealizadeh-via, it is a conscious design choice to not return everything in `predict`. Why: `sktime` provides unified interfaes, where all estimators have the same return. Returning 100 different things from `predict` would make that difficult, if not impossible.

You can get prediction intervals and quantiles from `predict_quantiles`, `predict_interval`, many models have these, see the forecasting tutorial.

Regarding model specific returns like `trend` (no other model has that?), there is no dedicated unified interface point for that.
One could always return it as part of `summary` or `get_fitted_params`, although that would not be specific to the forecasting horizon.

Let us know if you have a good idea, how to return the "model specific" things that depend on `fh`, without compromising the interface uniformity across all forecasters.

**Comment by fkiraly** [comment]
(no followup for 1/2 year, closing)

**Comment by brentonmallen1** [comment]
is there a preferred method to accessing the underlying forecaster in this case? potentially something like `forecaster._ModelClass.predict(...)`? So that the native predict call could be made and return all the values from the prophet model.

Or is there's some guidance around using `predict_quantiles` and `predict_interval` to also the [yhat value](https://github.com/facebook/prophet/blob/dc1df4cb23a150e14858afb34c9442401c0eb2fc/python/prophet/forecaster.py#L1287) that would otherwise come from the native predict call as it seems to be more than requesting something like 0.5 quantile prediction (I could be missing something). Would this involve making two predict calls; one to the `predict` method and one to the `predict_quantiles|interval` method?
