### ISSUE TITLE
[ENH] Adding CNTC DL model for classification

### ISSUE THREAD

**Issue by AurumnPegasus** [sktime/sktime#3153]
**Is your feature request related to a problem? Please describe.**
In line with discussions and #2894 , adding CNTC model for classification from sktime-dl

**Comment by AurumnPegasus** [comment]
Adding some notes here to help me better understand the model (and hopefully someone else if they were to work on it someday):

1. Time series data is fed into a CLSTM and CCNN networks simultaneously and is perceived differently. In the CLSTM block, the input data is viewed as a multivariate time series with a single time stamp. In contrast, the CCNN block receives univariate data with numerous time stamps

**Comment by AurumnPegasus** [comment]
Hey @James-Large  (tagging you since tony recommended I ask you about this):
I had a doubt with respect to the prepare_input function in the network. Can you just help me out by telling the expected shape of input X to the function? The file I am looking at is this: https://github.com/sktime/sktime-dl/blob/b565b7499f58f43da7314f1bf26eccce94e88134/sktime_dl/networks/_cntc.py#L10

also, in the model creation why are there 3 input layers? Regarding this doubt. there are 2 arms which are suggested in the paper, one is of CCNN and another is CLSTM. In the code written by the author (and in sktime-dl) the first arm has cnn-rnn-cnn arm (conv1, rnn1 which becomes conc1, and then conv2) and another is lstm arm (lstm1), both of which are then merged. From my understanding atleast, it seems that the arms are supposed to be cnn and lstm only (or maybe cnn-rnn and lstm? there was a concept of recurrant convolution mentioned in one of the references), but the current model doesnt seem to follow that. Is there something wrong in my understanding or is there a change in code? Please let me know!

**Comment by James-Large** [comment]
Hi @AurumnPegasus, to predicate this answer I've been out of the loop on sktime/-dl for some time. It looks like that architecture was imported by Jack Russon, who if I recall was a masters student last year and so maybe I'm easier to contact. 

On the model details, I can't have a read of the paper since I don't have academic institute access any more and it doesn't look like there's an arxiv/free version of the paper, however from the [original contextual CCN paper](https://www.researchgate.net/profile/Joongbo-Shin/publication/325423879_Contextual-CNN_A_Novel_Architecture_Capturing_Unified_Meaning_for_Sentence_Classification/links/5b8e9b0345851540d1c870fb/Contextual-CNN-A-Novel-Architecture-Capturing-Unified-Meaning-for-Sentence-Classification.pdf), the general idea is "combining recurrent connections with convolutional layer". I annoyingly can't find code for that original paper, but the architecture defined by CNTC looks like it follows it (RNN and CNN merged to make a CCNN as the first arm). I think in the [CNTC figures](https://raw.githubusercontent.com/AmaduFullah/CNTC_MODEL/master/model2.png) they've just simplified this into a single arm for figure-drawing purposes. 

The [CLSTM](https://arxiv.org/pdf/1602.06291.pdf) part ("To adapt the LSTM cell that takes words to a CLSTM cell that takes as input both words and topics,") in a TSC context seems to just be an LSTM with an expanded input to act as the contextual topics. In the original CNTC code this is defined [here](https://github.com/AmaduFullah/CNTC_MODEL/blob/master/cntc.ipynb) (it's a notebook so no line number links)
![image](https://user-images.githubusercontent.com/44509982/182811027-083ae869-244d-4935-ae19-86f7bdcef41a.png)
and then in the sktime-dl code defined in the [prepare_input function](https://github.com/sktime/sktime-dl/blob/b565b7499f58f43da7314f1bf26eccce94e88134/sktime_dl/networks/_cntc.py#L120).

So ultimately, to the best of my knowledge there being 3 input layers seems reasonable to me. The CNTC paper aggregated the CCNN architecture into one 'arm' for their model, but that itself is composed of the RNN and CNN inputs. I'd say also that regardless, faithfulness to the author's code is what (I think, others feel free to correct me) is important when integrating known/defined models that have code attached. If that's the architecture they implemented to get the results they reported and published, we should replicate the same. 

____________

On the input format to prepare_input, it looks like prepare_input is called in as a data processing step in the fit and predicts of the implementing model classes, [_after_](https://github.com/sktime/sktime-dl/blob/b565b7499f58f43da7314f1bf26eccce94e88134/sktime_dl/classification/_cntc.py#L157) the [call](https://github.com/sktime/sktime-dl/blob/b565b7499f58f43da7314f1bf26eccce94e88134/sktime_dl/classification/_cntc.py#L145) to [check_and_clean_data](https://github.com/sktime/sktime-dl/blob/b565b7499f58f43da7314f1bf26eccce94e88134/sktime_dl/utils/_data.py#L10)

check_and_clean_data takes (what I assume to still be) the sktime data format and converts it to a 3d np array of the form [instances][dimensions][timepoints], and so it looks like that's what prepare_input is expecting



Hope that helps, I won't be able to spend much more time on this today but it was a neat little foray back into deep learning literature for me, thanks
