### ISSUE TITLE
[BUG] make_reduction predict() does not work with sktime forecasters

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#3235]
**Describe the bug**
`make_reduction` does not work with `sktime` forecasters aka `scitype="time-series-regressor"`

```
TypeError: Invalid `fh`. The type of the passed `fh` values is not supported. Please use one of ('int', 'np.array', 'list', 'pd.RangeIndex', 'pd.PeriodIndex', 'pd.DatetimeIndex', 'pd.TimedeltaIndex'), but found: <class 'numpy.ndarray'>
```

**To Reproduce**

```python
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
from sktime.forecasting.model_selection import temporal_train_test_split
from sktime.forecasting.base import ForecastingHorizon
from sktime.forecasting.compose import make_reduction
from sktime.datasets import load_airline

y = load_airline()
y_train, y_test = temporal_train_test_split(y)
fh = ForecastingHorizon(y_test.index, is_relative=False)

forecaster = make_reduction(ExponentialSmoothing(), window_length=12, scitype="time-series-regressor")
forecaster.fit(y_train, fh=fh)
y_pred = forecaster.predict()
```

**Versions**
`main`

**Comment by aiwalter** [comment]
I would also propose to rename `"time-series-regressor"` to `"forecaster"` as scitype, I think that is better understandable

**Comment by fkiraly** [comment]
The scitype string currently is `"regressor"`, that inherits from `BaseRegressor` and is different from `"forecaster"` which inherits from `BaseForecaster`.

**Comment by fkiraly** [comment]
Silly question: why do tests currently not catch this?

**Comment by aiwalter** [comment]
@fkiraly is `time-series-regressor` an `sktime` forecaster? Or what is it?

**Comment by fkiraly** [comment]
> @fkiraly is time-series-regressor an sktime forecaster? Or what is it?

I think it's just the string used in `make_reduction` to indicate the argument is a time series regressor.

It is kind of redundant, since this information could be retrieved from the estimator by checking base class inheritance, or running the `scitype` utility on it.

The string used everywhere else, for time series regressors, is `"regressor"`, so the string here is also inconsistent with the rest of ``sktime``.

My preference would be to remove the type input and just infer it from the estimator.

**Comment by nyk2001** [comment]
I am getting the same error. How we can fix it ?

**Comment by aiwalter** [comment]
@nyk2001 i think its not meant to be used with forecasters
