### ISSUE TITLE
[ENH] Global alignment kernel for Kernel-based PCA in sktime

### ISSUE THREAD

**Issue by techtide** [sktime/sktime#340]
sktime currently includes in ``sktime.transformers.series_as_features.pca`` a method of doing ordinary principal component analysis of a series. I do not believe that it is possible at the moment to use a KernelPCA, specifically with the dynamic time warping based Global Alignment Kernel (which is used, for instance, in sktime's TimeSeriesSVC). It would be interesting and probably useful to have this included in sktime, and because of the existing implementation of the kernel, I do not think that it would be that difficult to add (perhaps it is already available?).

**Comment by mloning** [comment]
Thanks for suggesting this! Yes, there is an open issue on kernel work, see #52  for an overview. If you're working in this area, we really appreciate a PR, but this may be a larger project.

**Comment by fkiraly** [comment]
@techtide, @mloning, I remember that from a while ago - was anything ever implemented? Last thing I remember was @goastler working on this, but that was 2019. We could have another go at the kernel and distance style transformers and, say, connect them with PCA. Would you be interested, @techtide?

**Comment by fkiraly** [comment]
Here's the PR:
https://github.com/alan-turing-institute/sktime/pull/113
would be interesting to hear from @goastler

**Comment by techtide** [comment]
> @techtide, @mloning, I remember that from a while ago - was anything ever implemented? Last thing I remember was @goastler working on this, but that was 2019. We could have another go at the kernel and distance style transformers and, say, connect them with PCA. Would you be interested, @techtide?

I am quite busy at the moment, but I hope to be more available by at least June, so I may have a shot then. Is there any documentation for new contributors to the project?

**Comment by mloning** [comment]
@techtide Check out the contributing guide: https://github.com/alan-turing-institute/sktime/blob/master/CONTRIBUTING.md

**Comment by fkiraly** [comment]
@techtide, I found this old issue while looking for alignment & kernel related content.

Your contribution could be quite timely if you are interested to get back to this now!

It took a while, but we now have:
* base class and extension template for distances/kernels
* base class and extension template for aligners, e.g., GA or dtw

For extension templates, see the `extension_templates` folder in the root dir.

You can find details in [STEP 10](https://github.com/sktime/enhancement-proposals/blob/main/steps/10_alignment_warping_knn/step.md) of how things fit together.

An implementation or interface for the GA kernel as a kernel/distance, and/or an aligner would be greatly appreciated.
Any other sequence kernels and aligners too!

What would also be appreciated is an implementation of PCA that takes as component a kernel/distance following the new base class. This might be a little challenge, since we don't have a base class for unsupervised algorithms other than clustering currently, but you could take the clustering template.

Feel free to join us on slack or discord to coordinate.

**Comment by fkiraly** [comment]
?

**Comment by fkiraly** [comment]
closed by https://github.com/sktime/sktime/pull/5039, which interfaces the GA kernel from `tslearn`, now useable with any `sktime` estimator.
