### ISSUE TITLE
[ENH] Adding support for `@targetlabel` string identifier in `.ts` files

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#3412]
**Is your feature request related to a problem? Please describe.**
Regression datasets from [tseregression](http://tseregression.org/) have `.ts` files that makes use of `@targetlabel` as opposed to `@classlabel` to check whether the response variable is present of not.

Currently `sktime` only checks for `@classlabel`. So, loading a dataset like [ApplianceEnergy](https://zenodo.org/record/3902637#.Yx8DrnZBxEY) will not work.

**Describe the solution you'd like**
Add a check statement for `@targetlabel` the same way we currently do for `@classlabel`.

**Additional context**
I'd make a PR if this solution is passed by the maintainers.

**Comment by TonyBagnall** [comment]
hi, thanks for this, I think it is a good idea: I am in favour of adding a new tag for @targetlabel to indicate a regression problem with the response variable as the last value in file.

I think ideally we should just replace classlabel with target label, then have "continuous" to indicate a regression problem and the current system to label a classification problem, in a similar way to Weka. However, this will require a huge amount of changes in all the repo and will break a lot of code. So better to just do as you say now,  since it will not break anything in classification. 

On related note, I think the data loading still needs a bit of sorting out, so we will put that on the list for the project when it starts.
