### ISSUE TITLE
[ENH] Tuning order of transformers in pipelines as a hyper-parameter

### ISSUE THREAD

**Issue by aiwalter** [sktime/sktime#3439]
**Is your feature request related to a problem? Please describe.**
We have currently three sequential pipeline classes `TransformedTragetForecaster`, `ForecastingPipeline` and `TransformerPipeline`. Having several transformers chained raises the question which is the best order (permutation) of the given transformers.
For example in the pipeline below, what is the best order of transformers?
```python
    >>> pipe = TransformedTargetForecaster(
        steps=[
    ...     ("outlier", HampelFilter()),
    ...     ("impute", Imputer()),
    ...     ("detrend", Detrender()),
    ...     ("deseason", Deseasonalizer()),
    ...     ("minmax", TabularToSeriesAdaptor(MinMaxScaler())),
    ...     ("difference", Differencer()),
    ...     ("forecast", NaiveForecaster(strategy="drift")),
    ... ])
```

**Describe the solution you'd like**

To tune the permutations of transformers, we would need another parameter that allow to give several sortings of the steps.
A solution could look as follows:
```python
    >>> pipe = TransformedTargetForecaster(
        steps=[
    ...     ("outlier", HampelFilter()),
    ...     ("impute", Imputer()),
    ...     ("detrend", Detrender()),
    ...     ("deseason", Deseasonalizer()),
    ...     ("minmax", TabularToSeriesAdaptor(MinMaxScaler())),
    ...     ("difference", Differencer()),
    ...     ("forecast", NaiveForecaster(strategy="drift")),
    ... ],
    ... permutation=["difference", "outlier", "deseason", "detrend", "impute", "minmax", "forecast"],
    ... )
```
This could be implemented as a `Mixin` class so all sequential pipeline classes could inherit and implement it. To be discussed if `"forecast"` step should be part of `permutation` list or if it should just stay at position where it is given. The param `permutation` could also accept `permutation="all"` to try all `n!` combinations with `n` as number of given transformers.

**Describe alternatives you've considered**
I thought first of having a separate transformer composition for this, but now I think its actually best to integrate this into the existing pipeline classes.

**Additional context**
Grid search, tuning

@miraep8  would be interested about your feedback as you wrote the `MultiplexTransformer` which solves the 1:n selection of transformers.
Also pinging @benHeid and @fkiraly

**Comment by fkiraly** [comment]
Very interesting idea! This one is not implemented yet 😁 

On first sight, I would say, this should *not* be attached to the current pipeline classes, that's attaching "too much responsibility".

Options I can think of:

* descendants with the added functionality
* a `PermutationMultiplexer` or `PipelinePermuter` or `InferParams`, which takes as args: `permute_arg` = name of the argument that is list of estimators (default=`steps`), and a `permutation` (default=identity). It behaves like the wrapped estimator, but with `permute_arg` permuted by `permutation`

What would be nice in the second idea if it were polymorphic.

**Comment by aiwalter** [comment]
> that's attaching "too much responsibility"

I think that should not be an argument, we should always design from a user perspective and not how convenient it is for us to code it. Thats why I think the solution I propose is the most intuitive and user-friendly solution. Having another composition for this would look quite weird especially given that user already needs to nest `TransformedTargetForecaster` and `ForecastingPipeline` is transforming `y` and `X`. So I wouldnt want to request from user another pipeline nesting inside this.

> descendants with the added functionality

Can you explain this a bit more please?

**Comment by aiwalter** [comment]
@miraep8 and @benHeid could you pls have a look at the 2 PRs: #3596 and #3689 which provide different implementation proposals for this issue.

I dont have a strong preference, but I can see following points:
___

Delegator (PROs)
- having a separate class for a more exotic functionality
- isolation of logic
- we also have isolated `OptionalPassthrough` in a separate class, we could have done that also in base class. So having a delegator would follow what we did here in past

___

Delegator (CONs)
- More nesting required when using `TransformedTargetForecaster` and `ForecastingPipeline` together with `ForecastinGridSearchCV` there are already 3 levels of nesting, this could go up to 5 levels of nesting which is not very user friendly?
- This delegator is only applicable to the 3 pipeline classes, its not like `OptionalPassthrough` that can be applied to ANY transformer. So thats why might make more sense to have logic directly in the (base) classes implemented

**Comment by fkiraly** [comment]
I think this one is not entirely correct, it should work with any child of the `_HeterogenousEnsembleForecaster`

> This delegator is only applicable to the 3 pipeline classes, its not like OptionalPassthrough that can be applied to ANY transformer. So thats why might make more sense to have logic directly in the (base) classes implemented

That is:
* `EnsembleForecaster` (does sth non-trivial if used with non-commuting aggregation function)
* `StackingForecaster` - does sth non-trivial

**Comment by miraep8** [comment]
### On the general idea:
- I like the idea of it and can imagine a few instances where it could be useful, I am glad you suggested it @aiwalter 
- I think what would make this really powerful would be if we also wrote some permutation generation functions that could generate lists for testing within the grid search. (eg - maybe a topological ordering that constrains the ordering to a certain degree!) (not something that needs to be implemented now! Just throwing it out there as a design idea). 

### On implementations generally:
- I think switching the permutation away from lists of strings to lists of 0-based indices would be easier to implement and to use?   I could see the strings being particularly confusing in the case that we are using the same estimator twice and people are unfamiliar with the generated naming system.  This is likely just a personal preference, but I thought it worth noting! :)

### On specific implementations:
- I tried to leave a few comments in both PRs.
- My general feeling is that I have a slight preference for Franz's implementation, because I do agree that there are issues with having this logic in the base class. 
- However the clear drawback (in my mind) of Franz's implementation is that wrapping the pipeline in yet another layer of estimator feels somehow confusing and not user friendly.  Instead as a user I would expect step order I could tune without the need for yet another layer to be added.  Perhaps this is just personal taste in this matter, but I am concerned about what this might look like if we begin to have multiple problems we solve this way  - then the nesting could get out of hand?
- I also would be interested in verifying that all the tuning logic still works as expected now that there is another layer.  eg if I wanted to tune something else in the original pipe would - would we now need to tune permute.pipe.tunable_attribute (rather than pipe.tunable_attribute?  Would be worth looking more into how the current tuning workflows change if we add on a `Permute` layer. 
- But out of the two my feeling is that #3689 has a better chance of working out of the box and appeals to me more from a design perspective, so if it comes down to choosing one or the other that would be my preference.

### Possible Suggestion:
- I personally this would be a great problem to solve via composition rather than by inheritance or by adding in extra layers of estimators. 
- How I would envision this working is that the user can optionally pass a composable object to their pipeline which overrides the base logic for fetching steps and could take care of the logic of handling permutations.
- Kind of the mix of the two solutions in that the logic of how to handle composable components would probably live in HeterogenousMetaEstimator but the actual logic is totally separated from it, and leave open the possibility for more variety in the future! 
- If this is of interest - I could potentially mock up a solution. 
- I would still lean towards observing that Franz's solution does look like it would work and could be merged after verifying the additional issues I highlighted. 

Cheers!

**Comment by aiwalter** [comment]
Ok seems @miraep8 and @benHeid tend slightly towards delegator solution. @fkiraly do you mind to finalize it or should I?

**Comment by fkiraly** [comment]
> However the clear drawback (in my mind) of Franz's implementation is that wrapping the pipeline in yet another layer of estimator feels somehow confusing and not user friendly

I'm not 100% sure whether I would agree with this one, @miraep8. From a domain driven design perspective I feel it might be easier to wrap your head around pipeline and permutation separately, as separated concepts, than a pipeline with added permutation function.

This is from a perspective of someone who needs to learn about the pipeline concept *and* the permutation concept, because learning about the grid search class is necessarily where you start. So the two options for what you need to learn about first is (a) pipeline without permutation, or (b) pipeline with permutation. I think (a) is the easier first step, so the "learning staircase" is less steep with (a), as measured by "maximum step difference".
