### ISSUE TITLE
[BUG] EnsembleForecaster fails to fit with exogenous data on hierarchical data

### ISSUE THREAD

**Issue by shagn** [sktime/sktime#3961]
**Describe the bug**
After upgrading sktime from version 0.12 to 0.14 the fitting of an EnsembleForecaster on a hierarchical dataset fails when receiving exogenous data. 
Without exogeneous data the fitting works without problems. 
It fails with exogeneous data if the models are using the exogeneous data or not. 

**To Reproduce**
```python
import pandas as pd

from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.forecasting.compose import EnsembleForecaster
from sktime.forecasting.naive import NaiveForecaster
from sktime.forecasting.trend import PolynomialTrendForecaster

data = _make_hierarchical(
    hierarchy_levels = (2, 4),
    n_columns = 2,
    min_timepoints = 38,
    max_timepoints = 38, 
    index_type = "period",
)

target_col = "c0"
y_train = data.loc[:, [target_col]]
X_train =  data.drop(columns=[target_col])

forecasters = [    
    ("trend", PolynomialTrendForecaster()),
    ("naive", NaiveForecaster(strategy="last", sp=12)),
]
forecaster = EnsembleForecaster(forecasters=forecasters)

forecaster.fit(y=y_train, X=X_train)
```
![image](https://user-images.githubusercontent.com/16029092/208664020-95342334-997a-4993-9bb9-cf639dce546f.png)

**Expected behavior**
The EnsembleForecaster works also with exogenous data. 

**Additional context**
None

**Versions**
System:
    python: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0]
executable: /anaconda/envs/.../bin/python
   machine: Linux-5.15.0-1022-azure-x86_64-with-glibc2.17

Python dependencies:
          pip: 22.1.2
   setuptools: 65.5.0
      sklearn: 1.1.1
       sktime: 0.14.0
  statsmodels: 0.13.2
        numpy: 1.21.5
        scipy: 1.7.3
       pandas: 1.4.4
   matplotlib: 3.6.2
       joblib: 1.1.0
        numba: 0.56.4
     pmdarima: None
      tsfresh: None

**Comment by fkiraly** [comment]
Bug confirmed on python 3.8 and windows.

I also found the reason: both vectorization/broadcasting and the heterogeneous ensemble base class use the attribute `forecaster_` which leads to a recursion accudent.

The `EnsembleForecaster` should, however, never vectorize/broadcast, and this clash of parameters should never happen.

But, it did happen because the `X_inner_mtype` was incorrectly set, which erroneously triggered vectorization/broadcasting any time an `X` that is panel or hierarchical is passed.

Fixes in #3964, hopefully.
