### ISSUE TITLE
[BUG] Docs are not being built during CI check

### ISSUE THREAD

**Issue by achieveordie** [sktime/sktime#4097]
**Describe the bug**

I believe that all of the current PRs only show "Expected — Waiting for status to be reported" for `docs/readthedocs.org:sktime` check. I don't know what is causing this but it must be recent since I remember this check passing few days ago.

**To Reproduce**

**Expected behavior**

**Additional context**

See #4093, #4075, #4087 etc.

**Versions**
<details>

</details>

**Comment by fkiraly** [comment]
Hm, this seems to be a GitHub GUI issue?

Because if you check directly on `readthedocs`, it looks like it gets built:
https://readthedocs.org/projects/sktime/builds/

**Comment by miraep8** [comment]
Yes, have also been looking into this as its blocking a PR from one of the new contributors I am working with.  Curiously, if you look at checks that have run from the PR itself you see 18 (this number includes the ReadTheDocs build).  But if you actually click on the detailed test summary the ReadTheDocs build disappears from the count and isn't included in the overall test run graph.  
![image](https://user-images.githubusercontent.com/10511777/212096078-fd2284eb-7b52-4766-8a67-f1a77e7f36a3.png)

Now, perhaps this isn't surprising because the read the docs test (from what I can tell) isn't actually included in the test.yml file where we put together all the other tests (and I assume is just linked in from some other Github actions widget or add on? I am not totally sure how it works right now).  One potential solution that we could try out could be to explicitly use the [Github action](https://github.com/readthedocs/actions) for Read The Docs?  Just wondering if something might be up with how its currently running and it might be nice to have it run through the same interface as everything else?

**Comment by fkiraly** [comment]
I've temporarily removed the requirement for the readthedocs check to pass, so merges become possible again (if everything else runs).
I think it's the reporting that's failing, readthedocs still builds, see above.
