### ISSUE TITLE
[ENH] naming of symmetricMAPE vs adjustedMAPE - clarifying docstring

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4457]
_Originally posted by @mtorabirad in https://github.com/sktime/sktime/issues/1986#issuecomment-1470320909_

A minor point but shouldn't we call symmetricMAPE adjustedMAPE. After all, sMAPE is not really symmetric and the original developer of the Metric, Armstrong, never called it symmetricMAPE. https://www.youtube.com/watch?v=_uaJWg5eNpE&ab_channel=MLBoost

**Comment by fkiraly** [comment]
thanks for the comment, @mtorabirad - kindly note that we rarely look in closed PR for comments and suggestions for improvement, I found this by chance only.

I suppose you have a point - how would you call the metrics and/or clarify the docstring?
(PR with suggestions are also appreciated)

The main problem with renaming is, users might be (or, in fact, are quite certainly) importing the metrics in production systems, so this would need deprecation.

I think we can approach it by making clarifications in the docstring first.

I've also noticed some degree of incompleteness and inaccuracy in the metrics docstrings, here's the umbrella issue:
https://github.com/sktime/sktime/issues/4303
If you (or someone else) want to take care of MAPE metrics, that would be great! The issue contains an example.

**Comment by hazrulakmal** [comment]
It appears that the issue is just with the naming convention. I found a [blog](https://robjhyndman.com/hyndsight/smape/) that briefly discusses the literature on sMAPE. It seems that there is a disagreement on whether we should use sMAPE or aMAPE, but to be fair both just refer to the same metrics. In my opinion, I agree with you that improving the clarifications in the docstrings that symmetricMAPE and adjustedMAPE refer to the same equation would be a way forward. I would be happy to improve the docstring for MAPE metrics (mean and median).

**Comment by fkiraly** [comment]
ok, that would be great!

If there is controversy or inconsistency on naming, you could do it as in the `CRPS` metric and just list the different names in use.

(btw, I notice that th `CRPS` is lacking references, that would also be a good thing to add if you are working on metrics docstrings anyway)
