### ISSUE TITLE
[ENH] testing `sktime` without `pytest`

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4544]
@yarnabrina made us aware of a quite vexing issue that makes my head hurt:

1. some parts of `sktime` that are not tests require `pytest` to run, e.g., `check_estimator`
2. some parts of `sktime` might import modules that should be isolated but aren't and `import pytest`, e.g., `all_estimators`

Simple question: how do we test that `sktime` runs without `pytest`, which is currently not a core dependency (but was an implied dependency prior to the dependency cleanup in 0.18.0 and `scikit-base`)

The conundrum is, currently any testing assumes `pytest` present (because we are using `pytest` for testing!), so we cannot test under the condition that it isn't - because we are testing!

We should at least be able to test that there are no unisolated `pytest` imports.

The same question poses itself for `scikit-base` as well.

The main alternative is, probably, making `pytest` a core dependency of `sktime`.

**Comment by yarnabrina** [comment]
@fkiraly I may be wrong, but there is a chance that the `pytest` issue I faced in work pipelines are different from the one you have found. Can you please confirm?

This is a (hopefully) reproducible setup to duplicate my error.

## Environment

```Dockerfile
FROM python:3-slim-bullseye
RUN pip install "sktime>=0.18" statsforecast
```

## Codes

```pycon
>>> from sktime.forecasting.statsforecast import StatsForecastAutoARIMA
>>> model = StatsForecastAutoARIMA()
>>> model_clone = model.clone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/skbase/base/_base.py", line 164, in clone
    from skbase.testing.utils.deep_equals import deep_equals
  File "/usr/local/lib/python3.11/site-packages/skbase/testing/__init__.py", line 5, in <module>
    from skbase.testing.test_all_objects import (
  File "/usr/local/lib/python3.11/site-packages/skbase/testing/test_all_objects.py", line 14, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
>>>
```

## Comment

So, this line is the issue. I really feel equality check should be in `utils` instead of in `testing/utils`, and that'd probably solve the problem as that `deep_equals` does not sesm to need `pytest` after all.

https://github.com/sktime/skbase/blob/9a5c70c358ef89b06993148407d93c524141e07a/skbase/base/_base.py#L96

**Comment by fkiraly** [comment]
> I really feel equality check should be in utils instead of in testing/utils

Agreed, the coupling is accidental and was unfortunately not tested.

Trying to resolve these two issues:

* uncouple, move to `utils` - https://github.com/sktime/skbase/pull/178
* test for unisolated developer imports - https://github.com/sktime/skbase/pull/179
