### ISSUE TITLE
[BUG] Non informative Exception when fitting TimeSeriesKMeans with pd.Dataframe 

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#4898]
**Describe the bug**
The fitting of TimeSeriesKMeans with pd.Dataframe produces an TypeError that is not informative. 

**To Reproduce**

```python
from sktime.clustering.k_means import TimeSeriesKMeans
import numpy as np
import pandas as pd
data = np.random.normal(0,1, (50, 12))
data_df = pd.DataFrame(data)
TimeSeriesKMeans().fit(data)
TimeSeriesKMeans().fit(data_df) # <- This line raises the TypeError
```

The resulting error message is:

```
TypeError: X is not of a supported input data type.X must be of type np.ndarray or pd.DataFrame, found <class 'pandas.core.frame.DataFrame'>Use datatypes.check_is_mtype to check conformance with specifications.
```

**Expected behavior**
Based on the discussion in Discord: The problem is that the the error message from `check_is_mtype` is not passed on. The problem is not that the python type is wrong, but that no panel specification is complied with (e.g., `pd-multiindex` needs 2 `pd.MultiIndex` levels). The error message should be more specific about the problem, e.g., by passing on the `check_is_mtype` error messages, such as in forecasting.

**Comment by fkiraly** [comment]
FYI, I updated the problem description with details on `check_is_mtype`, by editing the post - please change or revert if not happy.

**Comment by achieveordie** [comment]
Based on my preliminary research on this bug, here are a few observations:
- The error message is actually arising from a failed `check_is_scitype()` against the type `Panel` rather than checking for any specific `mtype`. In fact, there are no checks for any particular `mtype`.
- The error arises from the base clusterer rather than `TimeSeriesKMeans`, which means this will be reproducible using other clusterers.
- Another interesting point that I noted was the lack of a "clusterer" label in the registry. I suppose at the very least `X_inner_mtype` should also have a clusterer tag appended in the second element.

Based on the observations, our current clusterer requires a more extensive validating method (and hence a more extensive failure message) and to make sure that they can be searched and indexed using tags, we also need to add them in the registry, wherever appropriate.
