### ISSUE TITLE
[ENH] rewrite `test_probabilistic_metrics` using proper `pytest` fixtures, or directly generate `pd.DataFrame`.

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#4907]
From profiling `pytest` test collection runs, we've discovered that, at current, major increase to runtime comes from `test_probabilistic_metrics` which fits and predicts every time upon module import.

This doesn't follow best `pytest` practice where fixture generation should not happen every time in the module, only at test time. The fit/predict also seems redundant, as we are only using the output.

There is a "software engineer" and a "data scientist" way to fix this, doing at least one should solve the problem - but it would be better to do both.

* the "software" appraoch would be moving the generation of the lists of `DataFrame`-s in lines 63 - 89 (`uni_data` etc) to `pytest` fixtures.
* the "data science" way would eliminate the need to fit/predict using the forecaster, after all we only use the output as a fixture, and it would be more robust to create these directly (i.e., using `pd.DataFrame` constructor) rather than getting them from an estimator's fit/predict

Good first issue for anyone who knows `pytest` or `pandas` - and it would help a lot of developers as the `pytest` test construction time is long.

**Comment by fkiraly** [comment]
FYI @eenticott-shell if you still remember this and/or have a good idea how to clear this up.

**Comment by julia-kraus** [comment]
Hello @fkiraly, I would like to contribute to this issue.

**Comment by fkiraly** [comment]
excellent, thanks!

**Comment by julia-kraus** [comment]
Hello Franz, 

I am am just pushing the PR. Regarding the changes I made:

I realized that in the "big parametrized test" `test_output`, there are 8 * 3 * 2 * 2 = 96 combinations and hence 96 subtests. My machine was struggling for two hours and then shut off. That's why I thought it would be better to separate the tests for quantile and interval forecasts. Also I realized that probably the quantile metrics belong only to quantile forecast and the interval metrics to interval forecasts, so some of the parameter combinations before were obsolete anyways. 

The smaller number of tests per function make it also easier to debug.

By separating, the tests run much faster. I kept the "big test" commented out in case you prefer that one. 

Regarding the `test_output` function. There are many nested assert. I think these should be refactored into separated tests, but that would be a separate issue.

Looking forward to your feedback,

Julia
