### ISSUE TITLE
[BUG] 'Differencer' returning strange results

### ISSUE THREAD

**Issue by MCRE-BE** [sktime/sktime#4965]
**Describe the bug**

When calling fit_transform and inverse_transform sequentially, I don't get the original series back when applying one or several lags. It seems to work fine with a PeriodIndex (like the example in the documentation), but does not work with a datetimeindex. I reproduced the issue with one of the default datasets included with SKTime (but I need to run a simple groupby to get it to daily level to match my own).

**To Reproduce**
```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_solar
y = load_solar()
y = y.groupby(by=pd.Grouper(level=0, freq="D")).sum()
display(y.plot())
```
![image](https://github.com/sktime/sktime/assets/99316631/a546da5b-f4b9-4628-9840-fec9c20bda2f)

```python
transformer = Differencer(lags=[1, 7])
y_transform = transformer.fit_transform(y)
display(y_transform.plot())
```
![image](https://github.com/sktime/sktime/assets/99316631/505b06f7-dfcd-47d2-a6ec-45c913eaf00e)

```python
y_revert = transformer.inverse_transform(y_transform)
y_revert = pd.DataFrame(y_revert, index=y_transform.index)
y_revert.plot()
```
![image](https://github.com/sktime/sktime/assets/99316631/20d16adf-4a5b-4d31-a4db-13d177a8d421)

**Expected behavior**
The returned series should be identical (or very close)

**Additional context**
I have the same problem with a much longer timeseries.

**Versions**
<details>
System:
    python: 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
executable: [c:\ProgramData\Miniconda3\envs\DLL_Forecast\python.exe](file:///C:/ProgramData/Miniconda3/envs/DLL_Forecast/python.exe)
   machine: Windows-10-10.0.19042-SP0

Python dependencies:
          pip: 23.2
       sktime: 0.21.0
      sklearn: 1.3.0
       skbase: 0.4.6
        numpy: 1.24.4
        scipy: 1.11.1
       pandas: 2.0.3
   matplotlib: 3.7.2
       joblib: 1.3.0
  statsmodels: 0.14.0
        numba: 0.57.1
     pmdarima: None
      tsfresh: None
   tensorflow: None
tensorflow_probability: None

</details>

**Comment by fkiraly** [comment]
reproduced on current `main`, windows, python 3.11

**Comment by fkiraly** [comment]
@MCRE-BE, I've investigated this and it is quite subtle.

The point is, `y_transform` has zeroes at the first eight indices, since you ran `Differencer` with the zero-fill default, for values that cannot be known (since earlier values are unknown).
Inverting that series with consecutive lags [1, 7] does not, mathematically, produce the original series.
(this is true only for a single lag, not multiple consecutive lags)

The differencer is smart enough to remember the original values *if they are not seen as part of `y_transform`* and fills them in, but in your case `y_transform` does have zeroes there.

If you were to run `Differencer` with `na_handling="drop_na"` or `"keep_na"`, those values would not be there, and the inversion would give you what you expect:

```python
import pandas as pd
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_airline

y = load_airline()
y = y.reset_index(drop=True)

transformer = Differencer(lags=[1, 7], na_handling="keep_na")

# these twp are now equal
y_transform = transformer.fit_transform(y)
y_revert = transformer.inverse_transform(y_transform)
```

Please let me know if it's not clear what happens, and whether you consider this problematic or counterintuitive.

An alternative behaviour for the `Differencer`, when given multiple consecutive lags, could be to fill the last sequential difference that is known, as opposed to zero.

That is, in the example, in `y_transform`, the zero-th value would be identical with the zero-th value of the original series, values 1 to 6 would be filled with the first differences of the original series, and value 7 would be the difference between the zero-th value of the original series and the 7-th first difference. This series, when inverted with the consecutive cumsum at lags [7, 1] would produce the original series.

But the non-zero values at the start would be weird to explain and understand - is this worse or better than the "fill zero" default?

What do you think?

**Comment by MCRE-BE** [comment]
hmmm the difference is indeed quite subtile. I have to admit, this bug only exists because of coding errors on my side. I don't use SKTime Piplines (yet) so I did code some of the steps individually.

- I did fill NaN's and zero's (but poorly, so some remained causing the bug)
- In the example above, I didn't think about checking the default parameter for na_handling. In my code I chose "keep_na". 

What I can tell you is : I am personnally never in favour to automatically doing or filling stuff. I would rather recommend setting errors to limit the use of the Differencer to known conditions that work :

- Don't inverse a timeseries where there are zero's in the first X and na_handling = "fill_zero"
- Don't inverse a timeseries with nan's (you check the freq, but that doesn't solve nan's)
- etc...

Thanks for taking the time to look at the problem though ! I'll see if I can adapt my code to make everything work now :-)

**Comment by MCRE-BE** [comment]
Ok. I've been running some more tests on my own dataset and I can't figure out why it's bugging.
The code is a bit messy but : 

- I have a timeseries that represents sales.
- I dropped all outliers, nan's and zero's
- Filled all the missing values with a simple XGBoost model
- This results in the following target variable. As far as I can see : No Zero's, No Nan's, no missing data
[data.csv](https://github.com/sktime/sktime/files/12212708/data.csv)

- I run an XGBoost forecast and I get the output below
[forecast.csv](https://github.com/sktime/sktime/files/12212758/forecast.csv)

- Reverting the forecasted values gives something strange. Any idea why?

```python
from sktime.transformations.series.difference import Differencer
transformer = Differencer(lags=[1, 7], na_handling="keep_na")
y_diff = transformer.fit_transform(y)

y_diff = y_diff.dropna()

model = xgboost.XGBRegressor()
model = model.fit(x[x.index.isin(y_diff.index)], y_diff)
yhat = model.predict(.x)

yhat = pd.Series(yhat, xgb.FeatureDataframe.index, name="yhat")
yhat = yhat.asfreq("D")
transformer.inverse_transform(yhat).plot()
```

![image](https://github.com/sktime/sktime/assets/99316631/62749e6f-deb9-419f-aafa-1b793897eb48)

**Comment by fkiraly** [comment]
Will be fixed by https://github.com/sktime/sktime/pull/4998, thanks for helping with the diagnosis, @MCRE-BE!

**Comment by MCRE-BE** [comment]
hmmm. I still have issues. 

```python
_Differencer = Differencer(
    lags=[1, 7,],
    na_handling="keep_na",
)
```
![image](https://github.com/sktime/sktime/assets/99316631/718950ef-124b-4e5b-805d-36ddd6488948)

my guess it's because of the zero in my first 7 locations. No?
The na_handling does not matter. The order of the lags does not matter either.

```python
| ds                  |    y |
|:--------------------|-----:|
| 2017-01-02 00:00:00 | 5068 |
| 2017-01-03 00:00:00 | 5714 |
| 2017-01-04 00:00:00 | 5757 |
| 2017-01-05 00:00:00 | 7269 |
| 2017-01-06 00:00:00 | 9541 |
| 2017-01-07 00:00:00 | 6392 |
| 2017-01-08 00:00:00 |    0 |
| 2017-01-09 00:00:00 | 7759 |
| 2017-01-10 00:00:00 | 6876 |
| 2017-01-11 00:00:00 | 6639 |
```

**Comment by MCRE-BE** [comment]
I did sync main, so normally the bugfix is in there. Could this be related that I am inverting a forecasted series?

The forecast seems normal and in-line with the differentiated-series, inverting the forecast produces this.

I'll try a toy example with forecast to see. Maybe it's not a bug, but just that this transformation is not OK for some forecasts

**Comment by benHeid** [comment]
That is strange. I will investigate it tomorrow. Sorry for the inconvenience.

**Comment by benHeid** [comment]
After a short investigation. I don't know what the problem is. At least the following line of code works without any exception and also visual inspection show on the main that y and y_revert are the same

```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_solar
import pandas as pd

y = load_solar()
y = y.groupby(by=pd.Grouper(level=0, freq="D")).sum()
display(y.plot())


transformer = Differencer(lags=[1, 7])
y_transform = transformer.fit_transform(y)
display(y_transform.plot())

y_revert = transformer.inverse_transform(y_transform)
y_revert = pd.DataFrame(y_revert, index=y_transform.index)
y_revert.plot()

pd.testing.assert_frame_equal(y.to_frame(), y_revert)
```

Running the code with an XGBoostRegressor also seems to be unproblemative to me.. (however, the xgboost forecast is really bad here...)

```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_longley
from sktime.forecasting.model_selection import temporal_train_test_split
import xgboost
import pandas as pd

transformer = Differencer(lags=[1, 7], na_handling="keep_na")
y, x = load_longley()
y_train, y_test, x_train, x_test = temporal_train_test_split(y, x)
y_diff = transformer.fit_transform(y_train)

y_diff = y_diff.dropna()

model = xgboost.XGBRegressor()
model = model.fit(x_train[x_train.index.isin(y_diff.index)], y_diff)
yhat = model.predict(x_test)
yhat = pd.Series(yhat, x_test.index, name="yhat")

y_revert = transformer.inverse_transform(yhat)
y_revert = pd.Series(y_revert, x_test.index, name="y_revert")

```

The results look as follows:
![image](https://github.com/sktime/sktime/assets/9725296/fac7fb38-7a97-4d99-a7ed-ac2e69be914a)


without any test train split, xgboost makes a perfect forecast and also the problem does not occur for me...

```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_longley
from sktime.forecasting.model_selection import temporal_train_test_split
import xgboost
import pandas as pd

transformer = Differencer(lags=[1, 7], na_handling="keep_na")
y, x = load_longley()
y_diff = transformer.fit_transform(y)

y_diff = y_diff.dropna()

model = xgboost.XGBRegressor()
model = model.fit(x[x.index.isin(y_diff.index)], y_diff)
yhat = model.predict(x)
yhat = pd.Series(yhat, x.index, name="yhat")

y_revert = transformer.inverse_transform(yhat)
y_revert = pd.Series(y_revert, x.index, name="y_revert")

```

Not y an y_revert have the same values.

![image](https://github.com/sktime/sktime/assets/9725296/05d83975-f003-4b8b-822b-f2f1b21ea2d0)


Can anyone confirm these results on main? 

@MCRE-BE how do you have installed sktime? Do you have installed it editable (option -e). If not, that might explain why the changes on main were not active.

**Comment by MCRE-BE** [comment]
> @MCRE-BE, how do you install sktime? Do you have installed it editable (option -e). If not, that might explain why the changes on main were not active.

Normally yes. I just blacked out the name of my employer as irrelevant.
<img width="566" alt="image" src="https://github.com/sktime/sktime/assets/99316631/64300632-6868-4b8b-a9ca-34a0034031ed">

hmmm deepdiving a bit and testing possible reasons or bugs. I might be a bit all over the place and unrelated, but bug is still there

### My baseline
```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_solar
y = load_solar()
y = y.groupby(by=pd.Grouper(level=0, freq="D")).sum()
```

### Bug 1 : Fitting with np.nan
If I fit a series without frequency, it produces a value as return that I cannot inverse. I would have expected this not to work.

```python
y.iloc[10:30] = np.nan
transformer = Differencer(lags=[1, 7], na_handling="keep_na")
y_transform = transformer.fit_transform(y.dropna())
transformer.inverse_transform(y_transform)
```

This error is not produced when nan's are present (so no dropna() in `fit_tranform`.
The behaviour is irrelevant of `na_handling`.
The different `na_handling `do work though, as all return different outputs (as expected).

### Test 2 : In-sample vs out-of-sample
I realized that I applied the `reverse_transform` on in-sample predictions and not only on out-of-sample predictions. This might be a difference, so I tested both options. Result is the same : from the start of prediciton, it's a race to infinite zero.

![image](https://github.com/sktime/sktime/assets/99316631/6c4ba2ee-04f2-42ee-835c-248c7d061a87)
![image](https://github.com/sktime/sktime/assets/99316631/6317dd10-8b8d-4520-9fde-f1614e5e5324)

### Test 3 : Dummy example

```python
from sktime.transformations.series.difference import Differencer
from sktime.datasets import load_solar
from sktime.forecasting.model_selection import temporal_train_test_split

y = load_solar()
y = y.groupby(by=pd.Grouper(level=0, freq="D")).sum()
x = y.index.isocalendar().astype(int)

transformer = Differencer(lags=[1, 7], na_handling="drop_na")

y_train, y_test, x_train, x_test = temporal_train_test_split(y, x)

y_diff = transformer.fit_transform(y_train)
y_diff = y_diff.dropna()

model = xgboost.XGBRegressor()
model = model.fit(x_train[x_train.index.isin(y_diff.index)], y_diff)
yhat = model.predict(x_test)
yhat = pd.Series(yhat, x_test.index, name="yhat")

y_revert = transformer.inverse_transform(yhat)
y_revert = pd.Series(y_revert, x_test.index, name="y_revert")

y_revert.plot()
y_train.plot()
y_test.plot()
plt.show()
```

![image](https://github.com/sktime/sktime/assets/99316631/1efd14d6-0b5c-4fb0-b059-03af3e868b1d)

Same issue. So I guess issue with XGBoost forecast ? Even if I have to admit that the forecast does not seem delirious. It's like a simple Naive forecast repeating the last season due to the limited amount of features I put in. 
![image](https://github.com/sktime/sktime/assets/99316631/bbc9d82b-6a7b-44f4-996b-3c28cbd9d4f9)

Does this help or am I delirious ❓

**Comment by benHeid** [comment]
I am definitely unsure what the problem is. But I am assuming that the problem is the result of XGBoost. The mean of the xgboost forecast is 0.8. The mean of y_diff 0.06. Thus, also the cumsum (operation to inverse the difference) is increasing. This is in line with the observation that the difference is also increasing. 

To test if this is a problem inherent to XGBoost or also caused by other models, I also tested the Linear Regression (mean=-0.19):

![image](https://github.com/sktime/sktime/assets/9725296/a2d74871-7099-41d6-833d-89a6bdfde938)

MLPRegressor (mean=54.5)
![image](https://github.com/sktime/sktime/assets/9725296/c29a0c06-c122-4c41-b5c9-6dbe30dc0b8e)

SVR (mean=-0.064)

![image](https://github.com/sktime/sktime/assets/9725296/1444fa74-389c-41cd-9caf-0165e99531fb)

These forecasts show that this problem also occurs when using the MLP but not for the LinearRegression and SVR. This indicates that this problem might be related to the regression model instead of the Differencer. 


Furthermore, the inverse transform on the transformed y_test also looks okay in the sense that it is not exploding. However, I think here could be an additional bug in the sense that the indices of y_test and transformer.transform(y_test) are differing, this is because the na_handling is done after the index selection. However, this should have no impact on the result here I suppose, since here we do not do any difference calculation on y_test. 

![image](https://github.com/sktime/sktime/assets/9725296/9128e5ed-5932-4d48-8efc-626f77763b9d)


With these observations, I believe that the Differencer is not the problem here (I know this is not a clear proof, but I think at least strong indicators). Concluding, I suppose that the reason for the weird result is the forecast. Any agreements or disagreements?

**Comment by MCRE-BE** [comment]
> With these observations, I believe that the Differencer is not the problem here (I know this is not a clear proof, but I think at least strong indicators). Concluding, I suppose that the reason for the weird result is the forecast. Any agreements or disagreements?

It's totally possible that the problem is the forecast. Annoying but possible. Likely Differencer suffers from the same problem as ARIMA forecasts : you need your timeseries to be stationary, etc... for it to work properly.

I'll close the issue.
