### ISSUE TITLE
[ENH] extend classifiers and regressors to multitarget

### ISSUE THREAD

**Issue by benHeid** [sktime/sktime#5182]
**Is your feature request related to a problem? Please describe.**
Currently, Regressor only supports single target predictions. But in some cases, it might be useful to predict more than one value at once. 

**Describe the solution you'd like**
In the discussion, @fkiraly proposed:
* add a tag (like in skpro) for multitarget yes/no
* if no, broadcast via VectorizedDF applied to y, in the base class. Same logic as in BaseForecaster

Based on that, in further PRs, direct support should be implemented where possible.

**TODOs**
* [ ] Add tags and the fallback behaviour in the BaseRegressor.
* [ ] Extend regressors that can directly support multi-target regression.
    * [ ] cnn
    * [ ] mcdncnn
    * [ ] resnet
    * [ ] rnn
    * [ ] tapnet?
    * [ ] ....

**Comment by fkiraly** [comment]
This also applies to classifiers the same way, so changed the title to include that.

**Comment by Vasudeva-bit** [comment]
We would like to extend capabilities of all the classifiers/regressors to deal with multivariate `y`. This has to be done as follows, 
1. If a classifier or regressor could deal with multivariate `y`, just fit it once and get the predictions.
2. Otherwise, broadcast estimator across columns in `y` with `method='clone'`, fit each estimator instance individually and get the predictions to corresponding `y` columns.

Also kindly let me know if we could distinguish algorithms that deal with single target `y` vs multi-target `y` with any tag?

**Comment by fkiraly** [comment]
> Also kindly let me know if we could distinguish algorithms that deal with single target `y` vs multi-target `y` with any tag?

There is no such tag yet, based on conventions in `sktime` and `sklearn` imo it should be called `"capability:multioutput"`.

The tag would have to be added in `registry._tags`, and I would set the defaults to `False` in the base classes.

For broadcasting, we can use `VectorizedDF.vectorize_est`.

**Comment by benHeid** [comment]
> Can we just extend in base class based on the tag `"capability:multioutput"` (yet to be added) to handle multioutput?
> 
> 
> 
> Or is it needed to extend each estimator with tag `"capability:multioutput"` `False` individually?
> 
> @benHeid 

I suppose setting false as a default has only be done in the base class. 

Only classes needs to be adapted that support multitarget prediction natively.

**Comment by benHeid** [comment]
@fkiraly or @Vasudeva-bit could you confirm that #5408 is solving this issue? If yes, we could close that issue

**Comment by fkiraly** [comment]
I think it does, yes.
