### ISSUE TITLE
[ENH] YfromX does not have the capability to return prediction intervals

### ISSUE THREAD

**Issue by ricardorodl** [sktime/sktime#5198]
**Is your feature request related to a problem? Please describe.**
YfromX does not have the capability to return:
- predict_interval
- predict_var
- predict_proba
- predict_quantiles

Yet all are mentioned as part of the methods available.

**Describe the solution you'd like**
Integration of these features to the class

**Describe alternatives you've considered**
Creating a custom reducer that includes any or all of them.

**Additional context**
![image](https://github.com/sktime/sktime/assets/122489141/28ffbef9-7a55-408b-bc83-c2ac9125b03a)

**Comment by fkiraly** [comment]
Interesting - currently, `YfromX` does not have probabilistic prediction capability since the `sklearn` regressors it reduces to do not have this.

You can currently add the capability via a probabilistic wrapper, e.g., `NaiveVariance`.

What I think the best way to proceed here is to ensure that `skpro` regressors (which have the proba prediction methods) can be passed - we can test this using the 2.0 upgrade of `skpro` that we intend to release around this week-end.

**Comment by ricardorodl** [comment]
Sounds good. In the meantime I'll test NaiveVariance as a wrapper and will report back.

**Comment by fkiraly** [comment]
(despite the failures the estimator should already work - failures are only from the "useless" edge case where no `X` is passed)
