### ISSUE TITLE
[BUG] search functionality on estimator overview page not working

### ISSUE THREAD

**Issue by alexfilothodoros** [sktime/sktime#5495]
**Describe the bug**

The search in estimator overview is not working

**To Reproduce**

Go to https://www.sktime.net/en/latest/estimator_overview.html and type sth, e.g. "SimpleRNNClassifier ". Click enter. 
-->

**Expected behavior**
Searching should work and find the keyword (e.g. "SimpleRNNClassifier"  in the table.

**Comment by fkiraly** [comment]
Confirmed on current `latest` docs and `stable` docs.

**Comment by fkiraly** [comment]
Related note, we probably ought to upgrade this page to also allow listing and searching for tags, if we're already looking for it - compare functionality in `all_estimators` and `all_tags`.

**Comment by fkiraly** [comment]
I think the magic happens (or should happen) in `setup(app)`, in `docs.source.conf`

**Comment by fkiraly** [comment]
Workaround is using ctrl-f

**Comment by yarnabrina** [comment]
I'm curious, did it ever work?

This is the search box code I think:

https://github.com/sktime/sktime/blob/c65d11b0af5c4c3cd43de9f7df426fed20092045/docs/source/estimator_overview.md?plain=1#L5-L8

This does not look related to the the line showing the table:

https://github.com/sktime/sktime/blob/c65d11b0af5c4c3cd43de9f7df426fed20092045/docs/source/estimator_overview.md?plain=1#L10-L11

(I've zero knowledge on HTML/JS/CSS stuff, but does not look like any search functionality, or any other link between text box and table).

**Comment by fkiraly** [comment]
> I'm curious, did it ever work?

I don't know - I always used either the python utilities directly, i.e., `all_estimators`, or ctrl-f.

**Comment by fkiraly** [comment]
> Is it a "good first issue" for people well versed with sphinx and/or frontend stuff?

Yes, I suppose so, I'll add the "good first issue" tag.

**Comment by Abhishektharu** [comment]
I think instead of form <p> is used in (Search the table ...) field and the entered text is not forwarded to any of the related file to perform action but  in (search docs .. class bd-search d-flex align-items-center) <form> tag is used and method is get. The text is forwarded to search.html.

**Comment by fkiraly** [comment]
@Abhishektharu, if you know how to fix it - appreciated!

**Comment by Abhishektharu** [comment]
I will try but I didn't find estimator_overview.html and other related html and javascript files and i don't know where do i get those files

**Comment by fkiraly** [comment]
the logic happens (or should happen), imo, in `setup(app)` (function), in `docs.source.conf` (file)

**Comment by Abhishektharu** [comment]
I think the codes of html and other files are stored in the cloud and retrieved through Python code.  Is it possible that they are being accessed through web APIs or other web-based services? I searched whole source code but didn't find anywhere. Also I searched in documentaton.

**Comment by Abhishektharu** [comment]
I found that the feature (search the table ) worked in v0.20.0  and previous but v0.20.1 and later caused problem. In console i found that (Uncaught ReferenceError: $ is not defined at estimator_overview.html:1992:9) this mainly happens when we don't include jQuery is not properly loaded or initialized in HTML and it is missing after v0.20.0. But it was included in v0.20.0.
![Screenshot 2023-10-31 131856](https://github.com/sktime/sktime/assets/51353634/0d5b3176-9b38-41ba-aef4-5b5a57a9b4bc)
probably including jQuery will solve the problem 
![Screenshot 2023-10-31 132037](https://github.com/sktime/sktime/assets/51353634/9e38a92c-40fc-427b-acf1-6bdcfee279fe)

**Comment by yarnabrina** [comment]
@Abhishektharu Based on a cursory look at https://github.com/sktime/sktime/compare/v0.20.0...v0.20.1, the only thing that can possibly affect is https://github.com/sktime/sktime/pull/4681. I tried to add a banner in case user is on latest instead of stable, but it didn't work. I should have reverted the PR long back, but forgot.

Can you check what happens if you revert this PR changes? If it solves search problems, that'd be great. 

Also, if you can help in that banner issue the PR failed to implement, that'd be great.

---

> I think the codes of html and other files are stored in the cloud and retrieved through Python code.

I don't know much details of `Sphinx`, but my understanding is `sphinx-build` creates javascript, html, etc. from the RST files and etc. created using `sphinx-apidoc`. Sometime during this, conf.py also gets executed and can create temporary files. I'm almost certain that it is not trying to pull any other files stored in some other cloud storage.

(@fkiraly can correct me if I am wrong here.)
