### ISSUE TITLE
[BUG] new CI elements still run if code quality checks fail

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#5530]
In CI, code quality checks should happen at first and stop any other CI from running.

For the new CI that does not seem to e the case though, see https://github.com/sktime/sktime/pull/5398 history.

**Comment by yarnabrina** [comment]
As part of recent CI changes, #5427 introduces a code quality check qorkflow, which must pass before the test workflows introduced by #5304. Both of these work completely independently of existing old CI workflows, which is intentional so that reverting or making any changes in new CI does not affect anything.

If you have an example where new code quality CI fails but new test CI is running even after that, that is completely impossible in my understanding because of these conditions in L28 and L32:

https://github.com/sktime/sktime/blob/441e334d680767d65777492726d2e4272bf49698/.github/workflows/test_code_quality.yml#L27-L34

Can you please share the link to the specific run you are referring to?

**Comment by fkiraly** [comment]
I think these: the "extras validation" ran, despite the two others failing with code quality issuesÖ

![Uploading image.png…]()

**Comment by fkiraly** [comment]
precisely, it is "extras validation 58" which spawned 135 jos, while "install and test 13630" and "validate code quality workflow 128" failed

**Comment by yarnabrina** [comment]
> As part of recent CI changes, https://github.com/sktime/sktime/pull/5427 introduces a code quality check qorkflow, which must pass before the test workflows introduced by https://github.com/sktime/sktime/pull/5304. Both of these work completely independently of existing old CI workflows, which is intentional so that reverting or making any changes in new CI does not affect anything.

Well, there was one more CI to check if modified extras are installable or not. This is a different CI independent of both of the abovementioned ones, and only run in those PR's that modifies `pyproject.toml`. This is a new CI logic which had no previous counterpart.

Currently, code quality (new or old) do not validate `pyproject.toml`, so I do not know if there is any logical dependency between these `validate_extras.yml` and `test_code_quality.yml`. The same can happen for `validate_datasets.yml` as well. Both of these are also configured to run on a schedule, so adding a dependency on code quality will affect those durations as well (not significantly).

As of now, `test_base.yml` and `test_components.yml` are dependent on `test_code_quality.yml`, and these two are the ones which will mostly run in normal PR's. Do you want to extend this code-quality-CI dependency to all CI workflows?

**Comment by fkiraly** [comment]
> Do you want to extend this code-quality-CI dependency to all CI workflows?

Imo that would be best, as code quality also catches syntax errors. We do not want to run 135 jobs if we know there are syntax errors, for instance.

**Comment by yarnabrina** [comment]
This was implemented by #5498, so probably can be closed. However as noted in #5559, strange behaviours were observed after this, which may or may not be caused by this.
