### ISSUE TITLE
[BUG] Graphical pipeline requires `X` in `fit` - contradiction to forecaster interface specs

### ISSUE THREAD

**Issue by sbuse** [sktime/sktime#5653]
**Describe the bug**

Building a pipeline with transforms working on `y` requires passing in a `X` in the fitting. I was hoping to be able to build a pipeline and transform `y` before passing it to the forecaster but that does not seem to work. 

**To Reproduce**

```python
from sktime.forecasting.compose import make_reduction
from sklearn.linear_model   import Ridge
from sktime.transformations.series.difference import Differencer
from sktime.transformations.series.lag import Lag
from sktime.datasets import load_airline
from sktime.split import temporal_train_test_split
from sktime.pipeline import Pipeline

y = load_airline()
y_train, y_test = temporal_train_test_split(y)

regressor = Ridge()
forecaster = make_reduction(regressor, window_length=12, strategy="recursive")

pipe = Pipeline()
pipe = pipe.add_step(Differencer(lags=[1,3,4,12]), "differencer", edges={"X": "y"})
pipe = pipe.add_step(Lag([1], index_out="original"),name="lag",edges={"X": "y"})
pipe = pipe.add_step(forecaster,
                  name="forecaster",
                  edges={
                      "X": ["lag","differencer"],
                      "y": "y"
                  })

pipe.fit(y=y_train) #<-- can't pass X=y_train since at predict time one would need to pass X=X_test=y_test
y_pred = pipe.predict(fh=[1, 2, 3])
```

**Expected behavior**

The expected behavior was no requirement for `X` in the fit function.

**Additional context**

**Versions**
<details>

System:
    python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
executable: [c:\Users\user\anaconda3\python.exe](file:///C:/Users/user/anaconda3/python.exe)
   machine: Windows-10-10.0.22621-SP0

Python dependencies:
          pip: 22.3.1
       sktime: 0.24.1
      sklearn: 1.0.2
       skbase: 0.6.1
        numpy: 1.23.5
        scipy: 1.9.3
       pandas: 1.4.4
   matplotlib: 3.6.2
       joblib: 1.1.1
        numba: 0.56.4
  statsmodels: 0.13.2
     pmdarima: None
statsforecast: None
      tsfresh: None
      tslearn: None
        torch: 1.13.1+cpu
   tensorflow: None
tensorflow_probability: None
</details>

**Comment by fkiraly** [comment]
Agreed - this is indeed a bug. There are not one but three related issues that I can see:

* `Pipeline` instances are polymorphic, if the instance is of forecaster type, it should conform with the interface. That means, `X` in `fit` cannot be required, because forecasters do not require `X` in `fit`.
* the type tag should be set to a base type, where possible - this is `object_type`, and it should be set to the string `"forecaster"` if the expected type is a forecaster
* the conformance should be tested, this can be achieved by implementing `get_test_params` and ensuring some test instances are of forecaster type. Fingers crossed, the test framework will collect these instances and subject them to forecaster specific tests. (we should check whether this is true, e.g., by inserting an obvious error)
