### ISSUE TITLE
[ENH] Improve SAX transformer

### ISSUE THREAD

**Issue by steenrotsman** [sktime/sktime#5732]
**Is your feature request related to a problem? Please describe.**
I have written an efficient implementation of SAX and wanted to contribute it here. I'm new so I might not fully understand the sktime API, but some aspects of this transformer seem off.

**Describe the solution you'd like**
A number of things stand out to me, I'm not sure if they are wrong per se. As I stated above, I might just misunderstand. Additionally, I would like to propose some breaking and non-breaking changes.

#### Possible issues
- The scitype is Series, but the mtype is numpy3D, which is a representation of the Panel scitype. The docstring lies that X is a nested dataframe.
    - As the SAX transformer is part of the `transformations.panel` module, should the scitype be changed to Panel? Or should the mtype just be changed to a numpy2D mtype (which happens as a first step of `_transform` anyway)?
- Output conversion is explicitly turned off, I think this is what causes a fail of `check_estimator`. Instead, a parameter `return_pandas_data_series` is accepted.
    - Should output conversion be enabled again, removing the output parameter?
- The `__author__` is not involved with sktime anymore, does it define the original author or the primary maintainer?
- `alphabet_size` and `word_length` are unnecessarily restricted.
- I think it is much clearer to calculate the breakpoints than hard-code them (can be done in a one-liner and is more precise).

I am willing to refactor the code to be more concise and efficient, and to work towards Deprecating existing issues.
I am happy to hear your feedback!

**Comment by fkiraly** [comment]
> I have written an efficient implementation of SAX and wanted to contribute it here.

That would be really great!

You could start off the current one if the changes are smaller, or add a new one (I would prefer that actually).
The current SAX is old code and indeed has a few issues, most notably the non-compliant output which has required an overrided in other classes that were coupled with it.

> The scitype is Series, but the mtype is numpy3D, which is a representation of the Panel scitype. The docstring lies that X is a nested dataframe. 

This is a long story, a shot summary:

* a long time ago, we distinguished "panel" and "series" transformers (panel-to-panel, series-to-series, series-to-primitives, panel-to-primitives), and these had a different interface. We realized that everyone got confused, especially since many "panel-to-panel" transformers that people implemented were actually transforming per individual series. That also made us realize that broadcasting by instance would allow to reduce the number of types.
* The distinction in `series` and `panel` module dates back from that time, probably we should resolve it at some point.
* In the transform-input, series-in series-out broadcasts to panel output if panel is input. Again I realize this is confusing, but I am not certain how this could be typed more intuitively - because of broadcasting up and down, series-to-series is the same as panel-to-panel. Suggestionsn welcome.

> Output conversion is explicitly turned off, I think this is what causes a fail of check_estimator. Instead, a parameter return_pandas_data_series is accepted.
> Should output conversion be enabled again, removing the output parameter?

In theory yes, exactly as you say.
But, unfortunately this transformer is a bit of a mess due to coupling with classes in the classification module which the same author contributed, and which assume the output in the non-compliant interface.

If one "fixes" the output of the `SAX` transformer, those other classes start breaking.
A clean new start would probably be better for now...
I haven't tried recently, some refactoring since then might have resolved issues, but I am not optimistic.

> The `__author__` is not involved with sktime anymore, does it define the original author or the primary maintainer?

That's an interesting question. We have had a number of cases where maintenance was abandoned, there are two discrepant roles:

* the original author who should be credited. That follows academic standards, so that shouldn't be purged even if the author leaves.
* the current maintainer. That follows the sktime governance rules, which has an algorithm maintainer role, and that role is lost for example when the author no longer engages.

We used to keep track of "scientific" authorship via the `__author__` field, and ownership via `CODEOWNERS`. Unfortunately it turned out that the idea we originally had in mind, that `CODEOWNERS` notifies the maintainer of pull requests, is not feasible, since GitHub does that only for GitHub accounts with write access, and by now we would have to give too many people write access which is not optimal security-wise.

We have not found a good solution, my best idea currently is adding the current maintainer as a tag.
Thoughts are appreciated.

> `alphabet_size` and `word_length` are unnecessarily restricted.

I guess so.

> I think it is much clearer to calculate the breakpoints than hard-code them (can be done in a one-liner and is more precise).

That is a "logic" decision and gives a slightly different algorithm, it's probably justifiable - I have not compared with the original paper on what is more faithful here. One could also give the user a choice via `breakpoint_method` or similar

> I am willing to refactor the code to be more concise and efficient, and to work towards Deprecating existing issues.
I am happy to hear your feedback!

That would be really great! Since as you say the original author is no longer engaged, the estimator's ownership has reverted to the core team (i.e., no specific owner). I would say it is up to you to decide whether you want to write a new estimator, e.g., just copy-wrapping your efficient code, or refactor this one - technical background is discussed above which you can take into account in pros and cons.

**Comment by steenrotsman** [comment]
Thanks for your extensive response! I have created new implementations for PAA and SAX (I'll make a pull request in a bit). From your answers and seeing the 'plumbing' layer in action while writing, I think I understand most issues now.

As for the calculation/hard-coding of breakpoints, the only difference is that calculating the breakpoints gives more precise values, while the hard-coded values are rounded to fewer significant digits. The original paper defines the breakpoints as the calculation and gives a table as illustration. Most implementations I've seen just copied the breakpoints table.

**Comment by fkiraly** [comment]
> As for the calculation/hard-coding of breakpoints, the only difference is that calculating the breakpoints gives more precise values, while the hard-coded values are rounded to fewer significant digits. The original paper defines the breakpoints as the calculation and gives a table as illustration. Most implementations I've seen just copied the breakpoints table.

I see - you could of course give the user a option the, because "most implementations" means it is established practice, and from a scientific perspective it is, hence, a potential point of comparison. Even if it is, from certain perspectives, not the best thing to do.

**Comment by fkiraly** [comment]
> From your answers and seeing the 'plumbing' layer in action while writing, I think I understand most issues now.

If you have any inputs on that, it would be appreciated! In writing, as a new issue, or here, or in the weekly meet-ups, all welcome - especially if critical of the status quo.

> I have created new implementations for PAA and SAX (I'll make a pull request in a bit). 

Looking forward to these! Worth considering the naming and locations if we have multiple. There are multiple options, examples in the repo are matrix profile, or ARIMA estimators.

**Comment by steenrotsman** [comment]
> Breakpoints
In my opinion, the issue is not so much scientific. The only reason the calculation can differ from the lookup table is when they round to different numbers of significant digits. Providing lookup tables is typically less precise (rounded to 2 or 3 significant digits), limits what alphabet sizes the user can pick (though providing a table with 20 rows is probably much more than any user would need), and clutters the code. Looking up the values is more efficient than calculating it, which might matter for very large panels. When I think about it, this is easily fixed by using `functools.cache` - I'll add that to the implementation.

> Plumbing
I like the design of the plumbing. As a developer, it's nice to be able to choose to work with NumPy, while the preference/defaults of sktime lean towards Pandas.

**Comment by fkiraly** [comment]
Re breakpoints/cache, I would say, let's not overcomplicate things for now - let's implement as you intended, and then revisit. Feels a bit like overkill to me.

**Comment by fkiraly** [comment]
Done in #5742
