### ISSUE TITLE
[ENH] in sample fh should raise `NotImplementedError` in `_check_fh`

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [sktime/sktime#6579]
Currently, `fit` in `BaseForecaster` does not raise in sample predicting error which cause errors by passing in sample fh to underlying `_fit`.

As suggested by @fkiraly in #6228, we should raise `NotImplementedError` in `_check_fh` and change "capability:insample" related skips to test for the error message instead.

**Comment by fkiraly** [comment]
I would say, not a bug, but a good idea to handle this in the boilerplate - current expectation is that `_fit` or `_predict` raise `NotImplementedError`, which is an expectation to the implementer not documented in the extension contract.

This should be easy by calling `ForecastingHorizon.is_all_out_of_sample` if the tag is `False` (no insample capability).

Boilerplate related, but imo a good first issue as the location and the change are very localized. Good for someone who has already contributed an estimator or otherwise worked on the base classes.

Do you want to pick it up, @Xinyu-Wu-0000? Or shall we leave it for someone else?

**Comment by Xinyu-Wu-0000** [comment]
> Do you want to pick it up, @Xinyu-Wu-0000? Or shall we leave it for someone else?

Yes, if we don't need to reserve some good first issue for other contributors.

**Comment by fkiraly** [comment]
> if we don't need to reserve some good first issue for other contributors.

Not in particluar, there are loads. Feel free to take this on.
