### ISSUE TITLE
[BUG] dependency checker detects incorrect version in case of multiple distributions of the same name installed, e.g., on databricks

### ISSUE THREAD

**Issue by toandaominh1997** [sktime/sktime#6987]
**Describe the bug**
The sktime utility is currently detecting and using the first scikit-learn version it encounters in the environment, which might be an outdated or lower-priority version. This causes issues when there are multiple versions of scikit-learn installed, and the higher-priority version is not selected.

**To Reproduce**

```python
from importlib.metadata import distributions
dists = distributions()
for dist in dists:
    if dist.metadata["Name"] == "scikit-learn":
        print(dist.metadata["Name"], dist.version)
```

**Expected behavior**
Output: 
```
scikit-learn 1.5.1
scikit-learn 1.1.1
```
So function _get_installed_packages_private()["scikit-learn"] => Return to 1.1.1

**Additional context**
This issue occurs when there are multiple versions of a package like scikit-learn installed in the environment. The distributions() function returns the versions in the order they are found, and the current implementation selects the last one. Reversing the iteration order would solve this issue by selecting the first version in the sys.path.

**Versions**

from sktime import show_versions; show_versions()
--> 0.32.1

</details>

**Comment by fkiraly** [comment]
I think this needs to be the *last* version in `sys.path`, which corresonds to the *first* version appearing in the iterator `distributions()`, but I suppose that's basically what you meant.

**Comment by fkiraly** [comment]
Side info: this issue was introduced in 0.31.1 through https://github.com/sktime/sktime/pull/6355 - which moved to using the import-less `importlib.distributions`, instead of importing `package.__version__` which would cause import chains.

While improving performance, the changed logic can fail in the case of multiple distributions of the same name, in the specific subcase where we are not just checking for presence of the package, but for specific version bounds.
