### ISSUE TITLE
[ENH] Avoid reloading TimesFM each time in expanding window

### ISSUE THREAD

**Issue by j-adamczyk** [sktime/sktime#7201]
**Is your feature request related to a problem? Please describe.**

TimesFM is zero-shot, and there is no fitting. However, in the expanding window strategy, when `ExpandingWindowSplitter` is used, the `_fit()` method is used every time. This results in very slow forecasting and huge memory requirements.

Concretely, when using TimesFM package, I got ~16 GB RAM requirements, model loading took ~17s, and forecasts are basically instant. When using `sktime`, memory grows up to 32 GB and I get OOM error.

**Describe the solution you'd like**

Initialization code with loading the model should be called during model initialization in `__init__`. This is that line: https://github.com/sktime/sktime/blob/6958687521ddeed7459a2b74d3314b550fa1dbb5/sktime/forecasting/timesfm_forecaster.py#L214.

**Additional context**

The same applies for other zero-shot models.

**Comment by j-adamczyk** [comment]
I just realized that `strategy` argument of splitter handles this. However, maybe it should be referenced in TimesFM docstring?

**Comment by fkiraly** [comment]
Hmm, there are very interesting issues related to deep learning and foundation models (or other large pretrained models) in particular that this touches!

* how much should `__init__` be allowed to do? E.g., when reserving memory. Currently, the intentional API design is to put any bottlenecks - memory or computation - into `_fit`. The reason is, usage of `__init__` defines a portable, near-instant specification language if this is the case, i.e., newly initialized instances form a "pure blueprint" rather than "doing something".
* should `_fit` be able to do caching and shared access to, say, loaded models, if we expect to instantiate many instances of the same model? This could be solved via a singleton or multiton oop pattern, but comes at a risk of introducing very hard to debug cross-instance side effects. This could also be an option, e.g., a "caching" parameter.

FYI @sktime/core-developers, especially @benHeid, @geetu040, @XinyuWuu, @pranavvp16

**Comment by fkiraly** [comment]
> I just realized that `strategy` argument of splitter handles this. However, maybe it should be referenced in TimesFM docstring?

Well, that's a realiztion that I have not had, thanks for pointing this out! Quite interesting.

Can you point me to the exact object and argument, do you mean `evaluate`?

Further, if you have investigated the code under the hood, could you point me to the precise object init or function call that causes multiple TimesFM instances to be loaded into memory? I would like to think about whether the caching/singleton architecture could in-principle solve this for multiple genuine `fit` calls, and how a caching layer would look like.

**Comment by j-adamczyk** [comment]
Right, sorry, this is in `evaluate`, not the splitter itself. I think that passing `strategy="no-update_params"` should call fit just once.

I am pretty sure that `_fit()` here (https://github.com/sktime/sktime/blob/6958687521ddeed7459a2b74d3314b550fa1dbb5/sktime/forecasting/timesfm_forecaster.py#L201) gets called multiple times by default with `strategy="refit"` (https://github.com/sktime/sktime/blob/6958687521ddeed7459a2b74d3314b550fa1dbb5/sktime/forecasting/model_evaluation/_functions.py#L215). Specifically the call to `load_from_checkpoint` loads the model weights (https://github.com/sktime/sktime/blob/6958687521ddeed7459a2b74d3314b550fa1dbb5/sktime/forecasting/timesfm_forecaster.py#L225C8-L225C60).

The simplest solution that I see for zero-shot forecasters is to set their `is_fitted` property to always be True after first fitting. Then any subsequent calls to `_fit()` after the first one would just instantly return.

**Comment by fkiraly** [comment]
I see, thanks.

> The simplest solution that I see for zero-shot forecasters is to set their `is_fitted` property to always be True after first fitting. Then any subsequent calls to `_fit()` after the first one would just instantly return.

That would "break" the API, but what we could do is have them behave like that, e.g., via caching.

**Comment by fkiraly** [comment]
Attempt here: #7204 - review and testing appreciated, @j-adamczyk.

**Comment by fkiraly** [comment]
@j-adamczyk, since you have an environment working with the `TimesFMForecaster`, it would be great if you could help us with testing and report on the memory usage!

I have created two variants with caching, but I am not sure if the tests are properly running:

https://github.com/sktime/sktime/pull/7203
https://github.com/sktime/sktime/pull/7205

**Comment by j-adamczyk** [comment]
@fkiraly I installed from branch https://github.com/sktime/sktime/pull/7204 and gain in performance is incredible. Just like using raw `timesfm` package, with exactly the same memory usage.

**Comment by fkiraly** [comment]
Could you also try #7205?

**Comment by geetu040** [comment]
btw @j-adamczyk I may ask, are you using the `source_package` or the sktime implementation?

**Comment by geetu040** [comment]
> @geetu040 I am using TimesFM package, I had problems with installing it with `sktime`. Some dependencies with `lingxo` and `jaxlib` dependencies, if I remember correctly.

I see. Are you on python 3.10 and linux?

@fkiraly I am working on pytorch based fork that should work on all machines in this PR https://github.com/sktime/sktime/pull/7155. But that will have to go through a deprecation cycle to be finally visible. Implementing this in pytorch will fix all dependency and testing problems. I think we should only care about the caching timesfm for now, reflecting the same with new pytorch implementation.

**Comment by j-adamczyk** [comment]
@geetu040 Python 3.10.15, Linux Ubuntu 24.04, managed with Poetry. I'm currently using `timesfm` package 1.1.0. Getting PyTorch version to work would be really nice.
