### ISSUE TITLE
[ENH] Fix failing output tests for the PoissonHMM detector

### ISSUE THREAD

**Issue by Alex-JG3** [sktime/sktime#7410]
## Summary

The following tests for the PoissonHMM detector fail and thus have been added to the list of excluded tests:

* `test_predict_points`
* `test_predict_segments`
* `test_transform_output_type`

We should fix PoissonHMM to make sure these tests pass.

## Related PR

The tests were added in #6958.

**Comment by y-mx** [comment]
Can I work on this issue?

**Comment by fkiraly** [comment]
@y-mx, sure!

Kindly be aware that there is a common base class for the HMM estimators, so issues could be in there - and there may be a joint fix for all esitmators by looking at that base class.

**Comment by y-mx** [comment]
Hi @fkiraly,
I think the issue is the HMMLearn base class `._predict` method returns an array in the dense representation, when the `BaseDetector` class expects a sparse representation. I'm not sure what is the best way to fix this without breaking other estimators, I would appreciate your guidance.

**Comment by Alex-JG3** [comment]
Since `BaseHMMLearn` inherits from `BaseDetector`, the `_predict` method for `BaseHMMLearn` should return a series to be compliant with `BaseDetector`.

So, I think we should change `_predict` in `BaseHMMLearn` so it returns a `Series`.
