### ISSUE TITLE
forecasting metrics (non-aggregate) should be able to return loss samples

### ISSUE THREAD

**Issue by fkiraly** [sktime/sktime#958]
Update: @RNKuhns has offboarded.

We´re also currently building probabilistic metrics, and we should ensure that the point prediction metrics are interface compatible (e.g., loss samples). I will look into this and take over @RNKuhns´ PRs.
---

For our future roadmap to include advanced benchmarking and testing capabilities, I think forecasting metrics will need to be able to return metrics of losses (in case the metric is some average).

For example, the commonly used Diebold-Mariano test to compare predictions losses of two predictions vs ground truth requires losses by forecast time point, not just an average.

This is perhaps easier to attach to the class version of the metrics (as a method) than to the function version?

Would be interested to hear your thoughts, @RNKuhns, @mloning, @aiwalter.

As a side point, not all metrics will have this, but they could return jackknife pseudo-samples by default, which would more easily give access to algorithms like jackknife and jackknife-plus estimates.

**Comment by RNKuhns** [comment]
@fkiraly this is something that @mloning and I talked about with the forecasting metrics interface. An option we considered was to have a function like `absolute_error(..., aggregation_type='mean')` instead of `mean_absolute_error(...)`.

The `aggregation_type` kwarg (or whatever we would have called it) could take values like: mean, median, max, etc and return either the metric aggregated as specificied (e.g. mean absolute error) or potentially un-aggregated (if users supplied `aggreagtation_type="samples"`. 

I believe that @mloning and I were worried about this type of interface being an issue for end users.

If we wanted to just go down the road that @fkiraly suggests with a method in the metric classes to return the metric applied to each sample (without aggregation) it probably wouldn't be much of a lift and we could avoid changing the user interface for the metric functions. 

The way I coded things for several of the metric groups (e.g. percentage error metrics), I already have a non-public function to apply the metric to each sample. The mean metric function uses this and then does the aggregation For example, I use `_percentage_error(...)` in multiple functions to calculate the non-aggregate part of the percentage error metrics). 

It would be easy to use this for any of the percentage error metrics to add a `samples` method (or whatever we want to name it):

```python

class MeanAbsolutePercentageError(_PercentageMetricFunctionWrapper):
    ...
    def samples(y_true, y_pred, ...)
        return _percentage_error(y_true, y_pred, ...)
```

In theory, it would be pretty simple to have the same setup for the other groups of metric functions (I've got a similar setup for the relative error metric functions and mean_asymmetric_error, so we'd just need a function for the scaled errors and the usual absolute/squared errors). 

We'd also have to decide how to adjust the `make_forecasting_scorer(func, ...)`. In the suggested setup `make_forecasting_scorer(func, sample_func, ...)` would need to accept the aggregate metric function (to be used when metric class is called) and a function to be used to return metric samples.

**Comment by fkiraly** [comment]
>I believe that @mloning and I were worried about this type of interface being an issue for end users.

Yes, I agree - especially if not really well documented, it can easily lead to confusion, or to low findability (e.g., how do you get median absolute error?)

>It would be easy to use this for any of the percentage error metrics to add a samples

I like that!
Except the name "samples", that is - that sounds more like a random draw from a probability distribution.

A higher abstraction variant would see objects that correspond to non-aggregate losses, e.g., `AbsolutePercentageError`, and then objects that construct the means. `MeanAbsolutePercentageError` could internally be defined as `MeanLoss(AbsolutePercentageError)`, and objects construted in this way would automatically have the `samples` function (or whatever we call it). Though this may be overdesign, I like yours more.

>would need to accept the aggregate metric function (to be used when metric class is called) and a function to be used to return metric samples.

Yes, I don't see a clear way forward here yet. By default, this could be applied element-wise, but it would only work for losses that are means.

**Comment by RNKuhns** [comment]
@fkiraly I'll push a PR with an example of this using the existing metrics shortly.

**Comment by fkiraly** [comment]
done by introduction of the `evaluate_by_index` method.
